'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyInformationalVersion("1.4.5"),  _
 Assembly: AssemblyCompany("SolidCP"),  _
 Assembly: AssemblyCopyright("Copyright © 2023 SolidCP."),  _
 Assembly: AssemblyFileVersion("1.4.9"),  _
 Assembly: AssemblyVersion("1.4.9")> 

