'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Reflection.AssemblyCompany("SolidCP"),  _
 Assembly: System.Reflection.AssemblyCopyright("Copyright © 2024 SolidCP."),  _
 Assembly: System.Reflection.AssemblyFileVersion("2.0.0"),  _
 Assembly: System.Reflection.AssemblyInformationalVersion("2.0.0"),  _
 Assembly: System.Reflection.AssemblyVersion("2.0.0")> 

