using System;
using System.Collections.Generic;
using SolidCP.EnterpriseServer.Data.Configuration;
using SolidCP.EnterpriseServer.Data.Entities;
using System.ComponentModel.DataAnnotations.Schema;
#if NetCore
using Microsoft.EntityFrameworkCore;
#endif
#if NetFX
using System.Data.Entity;
#endif

namespace SolidCP.EnterpriseServer.Data.Configuration;

public partial class QuotaConfiguration: EntityTypeConfiguration<Quota>
{
    public override void Configure() {

		if (IsCore && IsSqlite) Property(e => e.QuotaName).HasColumnType("TEXT COLLATE NOCASE");

#if NetCore
        Property(e => e.QuotaId).ValueGeneratedNever();
        Property(e => e.QuotaOrder).HasDefaultValue(1);
        Property(e => e.QuotaTypeId).HasDefaultValue(2);
        Property(e => e.ServiceQuota).HasDefaultValue(false);

        HasOne(d => d.Group).WithMany(p => p.Quota).HasConstraintName("FK_Quotas_ResourceGroups");

        HasOne(d => d.ItemType).WithMany(p => p.Quota).HasConstraintName("FK_Quotas_ServiceItemTypes");
#else
        HasRequired(d => d.Group).WithMany(p => p.Quota);
        HasRequired(d => d.ItemType).WithMany(p => p.Quota);
#endif

		#region Seed Data
		HasData(() => new Quota[] {
			new Quota() { QuotaId = 2, GroupId = 6, ItemTypeId = 7, QuotaDescription = "Databases", QuotaName = "MySQL4.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = true },
			new Quota() { QuotaId = 3, GroupId = 5, ItemTypeId = 5, QuotaDescription = "Databases", QuotaName = "MsSQL2000.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = true },
			new Quota() { QuotaId = 4, GroupId = 3, ItemTypeId = 9, QuotaDescription = "FTP Accounts", QuotaName = "FTP.Accounts", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = true },
			new Quota() { QuotaId = 12, GroupId = 8, ItemTypeId = 14, QuotaDescription = "Statistics Sites", QuotaName = "Stats.Sites", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = true },
			new Quota() { QuotaId = 13, GroupId = 2, ItemTypeId = 10, QuotaDescription = "Web Sites", QuotaName = "Web.Sites", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = true },
			new Quota() { QuotaId = 14, GroupId = 4, ItemTypeId = 15, QuotaDescription = "Mail Accounts", QuotaName = "Mail.Accounts", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = true },
			new Quota() { QuotaId = 15, GroupId = 5, ItemTypeId = 6, QuotaDescription = "Users", QuotaName = "MsSQL2000.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 18, GroupId = 4, ItemTypeId = 16, QuotaDescription = "Mail Forwardings", QuotaName = "Mail.Forwardings", QuotaOrder = 3,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 19, GroupId = 6, ItemTypeId = 8, QuotaDescription = "Users", QuotaName = "MySQL4.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 20, GroupId = 4, ItemTypeId = 17, QuotaDescription = "Mail Lists", QuotaName = "Mail.Lists", QuotaOrder = 6,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 24, GroupId = 4, ItemTypeId = 18, QuotaDescription = "Mail Groups", QuotaName = "Mail.Groups", QuotaOrder = 4,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 25, GroupId = 2, QuotaDescription = "ASP.NET 1.1", QuotaName = "Web.AspNet11", QuotaOrder = 3, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 26, GroupId = 2, QuotaDescription = "ASP.NET 2.0", QuotaName = "Web.AspNet20", QuotaOrder = 4, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 27, GroupId = 2, QuotaDescription = "ASP", QuotaName = "Web.Asp", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 28, GroupId = 2, QuotaDescription = "PHP 4.x", QuotaName = "Web.Php4", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 29, GroupId = 2, QuotaDescription = "PHP 5.x", QuotaName = "Web.Php5", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 30, GroupId = 2, QuotaDescription = "Perl", QuotaName = "Web.Perl", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 31, GroupId = 2, QuotaDescription = "Python", QuotaName = "Web.Python", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 32, GroupId = 2, QuotaDescription = "Virtual Directories", QuotaName = "Web.VirtualDirs", QuotaOrder = 9, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 33, GroupId = 2, QuotaDescription = "FrontPage", QuotaName = "Web.FrontPage", QuotaOrder = 10, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 34, GroupId = 2, QuotaDescription = "Custom Security Settings", QuotaName = "Web.Security", QuotaOrder = 11, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 35, GroupId = 2, QuotaDescription = "Custom Default Documents", QuotaName = "Web.DefaultDocs", QuotaOrder = 12, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 36, GroupId = 2, QuotaDescription = "Dedicated Application Pools", QuotaName = "Web.AppPools", QuotaOrder = 13, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 37, GroupId = 2, QuotaDescription = "Custom Headers", QuotaName = "Web.Headers", QuotaOrder = 14, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 38, GroupId = 2, QuotaDescription = "Custom Errors", QuotaName = "Web.Errors", QuotaOrder = 15, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 39, GroupId = 2, QuotaDescription = "Custom MIME Types", QuotaName = "Web.Mime", QuotaOrder = 16, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 40, GroupId = 4, QuotaDescription = "Max Mailbox Size", QuotaName = "Mail.MaxBoxSize", QuotaOrder = 2, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 41, GroupId = 5, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2000.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 42, GroupId = 5, QuotaDescription = "Database Backups", QuotaName = "MsSQL2000.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 43, GroupId = 5, QuotaDescription = "Database Restores", QuotaName = "MsSQL2000.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 44, GroupId = 5, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2000.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 45, GroupId = 6, QuotaDescription = "Database Backups", QuotaName = "MySQL4.Backup", QuotaOrder = 4, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 47, GroupId = 1, ItemTypeId = 20, QuotaDescription = "ODBC DSNs", QuotaName = "OS.ODBC", QuotaOrder = 6,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 48, GroupId = 7, QuotaDescription = "DNS Editor", QuotaName = "DNS.Editor", QuotaOrder = 1, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 49, GroupId = 4, QuotaDescription = "Max Group Recipients", QuotaName = "Mail.MaxGroupMembers", QuotaOrder = 5, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 50, GroupId = 4, QuotaDescription = "Max List Recipients", QuotaName = "Mail.MaxListMembers", QuotaOrder = 7, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 51, GroupId = 1, QuotaDescription = "Bandwidth, MB", QuotaName = "OS.Bandwidth", QuotaOrder = 2, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 52, GroupId = 1, QuotaDescription = "Disk space, MB", QuotaName = "OS.Diskspace", QuotaOrder = 1, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 53, GroupId = 1, QuotaDescription = "Domains", QuotaName = "OS.Domains", QuotaOrder = 3, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 54, GroupId = 1, QuotaDescription = "Sub-Domains", QuotaName = "OS.SubDomains", QuotaOrder = 4, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 55, GroupId = 1, QuotaDescription = "File Manager", QuotaName = "OS.FileManager", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 57, GroupId = 2, QuotaDescription = "CGI-BIN Folder", QuotaName = "Web.CgiBin", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 58, GroupId = 2, QuotaDescription = "Secured Folders", QuotaName = "Web.SecuredFolders", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 59, GroupId = 2, ItemTypeId = 25, QuotaDescription = "Shared SSL Folders", QuotaName = "Web.SharedSSL", QuotaOrder = 8,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 60, GroupId = 2, QuotaDescription = "Web Sites Redirection", QuotaName = "Web.Redirections", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 61, GroupId = 2, QuotaDescription = "Changing Sites Root Folders", QuotaName = "Web.HomeFolders", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 62, GroupId = 10, ItemTypeId = 21, QuotaDescription = "Databases", QuotaName = "MsSQL2005.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 63, GroupId = 10, ItemTypeId = 22, QuotaDescription = "Users", QuotaName = "MsSQL2005.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 64, GroupId = 10, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2005.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 65, GroupId = 10, QuotaDescription = "Database Backups", QuotaName = "MsSQL2005.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 66, GroupId = 10, QuotaDescription = "Database Restores", QuotaName = "MsSQL2005.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 67, GroupId = 10, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2005.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 68, GroupId = 11, ItemTypeId = 23, QuotaDescription = "Databases", QuotaName = "MySQL5.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 69, GroupId = 11, ItemTypeId = 24, QuotaDescription = "Users", QuotaName = "MySQL5.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 70, GroupId = 11, QuotaDescription = "Database Backups", QuotaName = "MySQL5.Backup", QuotaOrder = 4, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 71, GroupId = 1, QuotaDescription = "Scheduled Tasks", QuotaName = "OS.ScheduledTasks", QuotaOrder = 9, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 72, GroupId = 1, QuotaDescription = "Interval Tasks Allowed", QuotaName = "OS.ScheduledIntervalTasks", QuotaOrder = 10, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 73, GroupId = 1, QuotaDescription = "Minimum Tasks Interval, minutes", QuotaName = "OS.MinimumTaskInterval", QuotaOrder = 11, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 74, GroupId = 1, QuotaDescription = "Applications Installer", QuotaName = "OS.AppInstaller", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 75, GroupId = 1, QuotaDescription = "Extra Application Packs", QuotaName = "OS.ExtraApplications", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 77, GroupId = 12, PerOrganization = 1, QuotaDescription = "Organization Disk Space, MB", QuotaName = "Exchange2007.DiskSpace", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 78, GroupId = 12, PerOrganization = 1, QuotaDescription = "Mailboxes per Organization", QuotaName = "Exchange2007.Mailboxes", QuotaOrder = 3,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 79, GroupId = 12, PerOrganization = 1, QuotaDescription = "Contacts per Organization", QuotaName = "Exchange2007.Contacts", QuotaOrder = 4,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 80, GroupId = 12, PerOrganization = 1, QuotaDescription = "Distribution Lists per Organization", QuotaName = "Exchange2007.DistributionLists", QuotaOrder = 5,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 81, GroupId = 12, PerOrganization = 1, QuotaDescription = "Public Folders per Organization", QuotaName = "Exchange2007.PublicFolders", QuotaOrder = 6,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 83, GroupId = 12, QuotaDescription = "POP3 Access", QuotaName = "Exchange2007.POP3Allowed", QuotaOrder = 9, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 84, GroupId = 12, QuotaDescription = "IMAP Access", QuotaName = "Exchange2007.IMAPAllowed", QuotaOrder = 11, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 85, GroupId = 12, QuotaDescription = "OWA/HTTP Access", QuotaName = "Exchange2007.OWAAllowed", QuotaOrder = 13, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 86, GroupId = 12, QuotaDescription = "MAPI Access", QuotaName = "Exchange2007.MAPIAllowed", QuotaOrder = 15, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 87, GroupId = 12, QuotaDescription = "ActiveSync Access", QuotaName = "Exchange2007.ActiveSyncAllowed", QuotaOrder = 17, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 88, GroupId = 12, QuotaDescription = "Mail Enabled Public Folders Allowed", QuotaName = "Exchange2007.MailEnabledPublicFolders", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 94, GroupId = 2, QuotaDescription = "ColdFusion", QuotaName = "Web.ColdFusion", QuotaOrder = 17, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 95, GroupId = 2, QuotaDescription = "Web Application Gallery", QuotaName = "Web.WebAppGallery", QuotaOrder = 1, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 96, GroupId = 2, QuotaDescription = "ColdFusion Virtual Directories", QuotaName = "Web.CFVirtualDirectories", QuotaOrder = 18, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 97, GroupId = 2, QuotaDescription = "Remote web management allowed", QuotaName = "Web.RemoteManagement", QuotaOrder = 20, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 100, GroupId = 2, QuotaDescription = "Dedicated IP Addresses", QuotaName = "Web.IPAddresses", QuotaOrder = 19, QuotaTypeId = 2,
				ServiceQuota = true },
			new Quota() { QuotaId = 102, GroupId = 4, QuotaDescription = "Disable Mailbox Size Edit", QuotaName = "Mail.DisableSizeEdit", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 103, GroupId = 6, QuotaDescription = "Max Database Size", QuotaName = "MySQL4.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 104, GroupId = 6, QuotaDescription = "Database Restores", QuotaName = "MySQL4.Restore", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 105, GroupId = 6, QuotaDescription = "Database Truncate", QuotaName = "MySQL4.Truncate", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 106, GroupId = 11, QuotaDescription = "Max Database Size", QuotaName = "MySQL5.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 107, GroupId = 11, QuotaDescription = "Database Restores", QuotaName = "MySQL5.Restore", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 108, GroupId = 11, QuotaDescription = "Database Truncate", QuotaName = "MySQL5.Truncate", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 110, GroupId = 90, ItemTypeId = 75, QuotaDescription = "Databases", QuotaName = "MySQL8.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 111, GroupId = 90, ItemTypeId = 76, QuotaDescription = "Users", QuotaName = "MySQL8.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 112, GroupId = 90, QuotaDescription = "Database Backups", QuotaName = "MySQL8.Backup", QuotaOrder = 4, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 113, GroupId = 90, QuotaDescription = "Max Database Size", QuotaName = "MySQL8.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 114, GroupId = 90, QuotaDescription = "Database Restores", QuotaName = "MySQL8.Restore", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 115, GroupId = 90, QuotaDescription = "Database Truncate", QuotaName = "MySQL8.Truncate", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 120, GroupId = 91, ItemTypeId = 75, QuotaDescription = "Databases", QuotaName = "MySQL9.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 121, GroupId = 91, ItemTypeId = 76, QuotaDescription = "Users", QuotaName = "MySQL9.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 122, GroupId = 91, QuotaDescription = "Database Backups", QuotaName = "MySQL9.Backup", QuotaOrder = 4, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 123, GroupId = 91, QuotaDescription = "Max Database Size", QuotaName = "MySQL9.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 124, GroupId = 91, QuotaDescription = "Database Restores", QuotaName = "MySQL9.Restore", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 125, GroupId = 91, QuotaDescription = "Database Truncate", QuotaName = "MySQL9.Truncate", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 200, GroupId = 20, ItemTypeId = 200, PerOrganization = 1, QuotaDescription = "SharePoint Site Collections", QuotaName = "HostedSharePoint.Sites",
				QuotaOrder = 1, QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 203, GroupId = 10, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2005.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 204, GroupId = 5, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2000.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 205, GroupId = 13, ItemTypeId = 29, QuotaDescription = "Organizations", QuotaName = "HostedSolution.Organizations", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 206, GroupId = 13, ItemTypeId = 30, PerOrganization = 1, QuotaDescription = "Users", QuotaName = "HostedSolution.Users",
				QuotaOrder = 2, QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 207, GroupId = 13, PerOrganization = 1, QuotaDescription = "Domains per Organizations", QuotaName = "HostedSolution.Domains", QuotaOrder = 3,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 208, GroupId = 20, QuotaDescription = "Max site storage, MB", QuotaName = "HostedSharePoint.MaxStorage", QuotaOrder = 2, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 209, GroupId = 21, PerOrganization = 1, QuotaDescription = "Full licenses per organization", QuotaName = "HostedCRM.Users", QuotaOrder = 2,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 210, GroupId = 21, QuotaDescription = "CRM Organization", QuotaName = "HostedCRM.Organization", QuotaOrder = 1, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 211, GroupId = 22, ItemTypeId = 31, QuotaDescription = "Databases", QuotaName = "MsSQL2008.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 212, GroupId = 22, ItemTypeId = 32, QuotaDescription = "Users", QuotaName = "MsSQL2008.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 213, GroupId = 22, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2008.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 214, GroupId = 22, QuotaDescription = "Database Backups", QuotaName = "MsSQL2008.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 215, GroupId = 22, QuotaDescription = "Database Restores", QuotaName = "MsSQL2008.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 216, GroupId = 22, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2008.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 217, GroupId = 22, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2008.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 218, GroupId = 23, ItemTypeId = 37, QuotaDescription = "Databases", QuotaName = "MsSQL2012.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 219, GroupId = 23, ItemTypeId = 38, QuotaDescription = "Users", QuotaName = "MsSQL2012.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 220, GroupId = 1, HideQuota = true, QuotaDescription = "Domain Pointers", QuotaName = "OS.DomainPointers", QuotaOrder = 5,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 221, GroupId = 23, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2012.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 222, GroupId = 23, QuotaDescription = "Database Backups", QuotaName = "MsSQL2012.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 223, GroupId = 23, QuotaDescription = "Database Restores", QuotaName = "MsSQL2012.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 224, GroupId = 23, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2012.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 225, GroupId = 23, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2012.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 230, GroupId = 13, QuotaDescription = "Allow to Change UserPrincipalName", QuotaName = "HostedSolution.AllowChangeUPN", QuotaOrder = 4, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 300, GroupId = 30, ItemTypeId = 33, QuotaDescription = "Number of VPS", QuotaName = "VPS.ServersNumber", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 301, GroupId = 30, QuotaDescription = "Allow user to create VPS", QuotaName = "VPS.ManagingAllowed", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 302, GroupId = 30, QuotaDescription = "Number of CPU cores", QuotaName = "VPS.CpuNumber", QuotaOrder = 3, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 303, GroupId = 30, QuotaDescription = "Boot from CD allowed", QuotaName = "VPS.BootCdAllowed", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 304, GroupId = 30, QuotaDescription = "Boot from CD", QuotaName = "VPS.BootCdEnabled", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 305, GroupId = 30, QuotaDescription = "RAM size, MB", QuotaName = "VPS.Ram", QuotaOrder = 4, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 306, GroupId = 30, QuotaDescription = "Hard Drive size, GB", QuotaName = "VPS.Hdd", QuotaOrder = 5, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 307, GroupId = 30, QuotaDescription = "DVD drive", QuotaName = "VPS.DvdEnabled", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 308, GroupId = 30, QuotaDescription = "External Network", QuotaName = "VPS.ExternalNetworkEnabled", QuotaOrder = 10, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 309, GroupId = 30, QuotaDescription = "Number of External IP addresses", QuotaName = "VPS.ExternalIPAddressesNumber", QuotaOrder = 11, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 310, GroupId = 30, QuotaDescription = "Private Network", QuotaName = "VPS.PrivateNetworkEnabled", QuotaOrder = 13, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 311, GroupId = 30, QuotaDescription = "Number of Private IP addresses per VPS", QuotaName = "VPS.PrivateIPAddressesNumber", QuotaOrder = 14, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 312, GroupId = 30, QuotaDescription = "Number of Snaphots", QuotaName = "VPS.SnapshotsNumber", QuotaOrder = 9, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 313, GroupId = 30, QuotaDescription = "Allow user to Start, Turn off and Shutdown VPS", QuotaName = "VPS.StartShutdownAllowed", QuotaOrder = 15, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 314, GroupId = 30, QuotaDescription = "Allow user to Pause, Resume VPS", QuotaName = "VPS.PauseResumeAllowed", QuotaOrder = 16, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 315, GroupId = 30, QuotaDescription = "Allow user to Reboot VPS", QuotaName = "VPS.RebootAllowed", QuotaOrder = 17, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 316, GroupId = 30, QuotaDescription = "Allow user to Reset VPS", QuotaName = "VPS.ResetAlowed", QuotaOrder = 18, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 317, GroupId = 30, QuotaDescription = "Allow user to Re-install VPS", QuotaName = "VPS.ReinstallAllowed", QuotaOrder = 19, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 318, GroupId = 30, QuotaDescription = "Monthly bandwidth, GB", QuotaName = "VPS.Bandwidth", QuotaOrder = 12, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 319, GroupId = 31, PerOrganization = 1, QuotaName = "BlackBerry.Users", QuotaOrder = 1, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 320, GroupId = 32, PerOrganization = 1, QuotaName = "OCS.Users", QuotaOrder = 1, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 321, GroupId = 32, QuotaName = "OCS.Federation", QuotaOrder = 2, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 322, GroupId = 32, QuotaName = "OCS.FederationByDefault", QuotaOrder = 3, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 323, GroupId = 32, QuotaName = "OCS.PublicIMConnectivity", QuotaOrder = 4, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 324, GroupId = 32, QuotaName = "OCS.PublicIMConnectivityByDefault", QuotaOrder = 5, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 325, GroupId = 32, QuotaName = "OCS.ArchiveIMConversation", QuotaOrder = 6, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 326, GroupId = 32, QuotaName = "OCS.ArchiveIMConvervationByDefault", QuotaOrder = 7, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 327, GroupId = 32, QuotaName = "OCS.ArchiveFederatedIMConversation", QuotaOrder = 8, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 328, GroupId = 32, QuotaName = "OCS.ArchiveFederatedIMConversationByDefault", QuotaOrder = 9, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 329, GroupId = 32, QuotaName = "OCS.PresenceAllowed", QuotaOrder = 10, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 330, GroupId = 32, QuotaName = "OCS.PresenceAllowedByDefault", QuotaOrder = 10, QuotaTypeId = 1, ServiceQuota = false },
			new Quota() { QuotaId = 331, GroupId = 2, QuotaDescription = "ASP.NET 4.0", QuotaName = "Web.AspNet40", QuotaOrder = 4, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 332, GroupId = 2, QuotaDescription = "SSL", QuotaName = "Web.SSL", QuotaOrder = 21, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 333, GroupId = 2, QuotaDescription = "Allow IP Address Mode Switch", QuotaName = "Web.AllowIPAddressModeSwitch", QuotaOrder = 22, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 334, GroupId = 2, QuotaDescription = "Enable Hostname Support", QuotaName = "Web.EnableHostNameSupport", QuotaOrder = 23, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 344, GroupId = 2, QuotaDescription = "htaccess", QuotaName = "Web.Htaccess", QuotaOrder = 9, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 345, GroupId = 40, ItemTypeId = 35, QuotaDescription = "Number of VPS", QuotaName = "VPSForPC.ServersNumber", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 346, GroupId = 40, QuotaDescription = "Allow user to create VPS", QuotaName = "VPSForPC.ManagingAllowed", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 347, GroupId = 40, QuotaDescription = "Number of CPU cores", QuotaName = "VPSForPC.CpuNumber", QuotaOrder = 3, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 348, GroupId = 40, QuotaDescription = "Boot from CD allowed", QuotaName = "VPSForPC.BootCdAllowed", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 349, GroupId = 40, QuotaDescription = "Boot from CD", QuotaName = "VPSForPC.BootCdEnabled", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 350, GroupId = 40, QuotaDescription = "RAM size, MB", QuotaName = "VPSForPC.Ram", QuotaOrder = 4, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 351, GroupId = 40, QuotaDescription = "Hard Drive size, GB", QuotaName = "VPSForPC.Hdd", QuotaOrder = 5, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 352, GroupId = 40, QuotaDescription = "DVD drive", QuotaName = "VPSForPC.DvdEnabled", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 353, GroupId = 40, QuotaDescription = "External Network", QuotaName = "VPSForPC.ExternalNetworkEnabled", QuotaOrder = 10, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 354, GroupId = 40, QuotaDescription = "Number of External IP addresses", QuotaName = "VPSForPC.ExternalIPAddressesNumber", QuotaOrder = 11, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 355, GroupId = 40, QuotaDescription = "Private Network", QuotaName = "VPSForPC.PrivateNetworkEnabled", QuotaOrder = 13, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 356, GroupId = 40, QuotaDescription = "Number of Private IP addresses per VPS", QuotaName = "VPSForPC.PrivateIPAddressesNumber", QuotaOrder = 14, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 357, GroupId = 40, QuotaDescription = "Number of Snaphots", QuotaName = "VPSForPC.SnapshotsNumber", QuotaOrder = 9, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 358, GroupId = 40, QuotaDescription = "Allow user to Start, Turn off and Shutdown VPS", QuotaName = "VPSForPC.StartShutdownAllowed", QuotaOrder = 15, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 359, GroupId = 40, QuotaDescription = "Allow user to Pause, Resume VPS", QuotaName = "VPSForPC.PauseResumeAllowed", QuotaOrder = 16, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 360, GroupId = 40, QuotaDescription = "Allow user to Reboot VPS", QuotaName = "VPSForPC.RebootAllowed", QuotaOrder = 17, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 361, GroupId = 40, QuotaDescription = "Allow user to Reset VPS", QuotaName = "VPSForPC.ResetAlowed", QuotaOrder = 18, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 362, GroupId = 40, QuotaDescription = "Allow user to Re-install VPS", QuotaName = "VPSForPC.ReinstallAllowed", QuotaOrder = 19, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 363, GroupId = 40, QuotaDescription = "Monthly bandwidth, GB", QuotaName = "VPSForPC.Bandwidth", QuotaOrder = 12, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 364, GroupId = 12, QuotaDescription = "Keep Deleted Items (days)", QuotaName = "Exchange2007.KeepDeletedItemsDays", QuotaOrder = 19, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 365, GroupId = 12, QuotaDescription = "Maximum Recipients", QuotaName = "Exchange2007.MaxRecipients", QuotaOrder = 20, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 366, GroupId = 12, QuotaDescription = "Maximum Send Message Size (Kb)", QuotaName = "Exchange2007.MaxSendMessageSizeKB", QuotaOrder = 21, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 367, GroupId = 12, QuotaDescription = "Maximum Receive Message Size (Kb)", QuotaName = "Exchange2007.MaxReceiveMessageSizeKB", QuotaOrder = 22, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 368, GroupId = 12, QuotaDescription = "Is Consumer Organization", QuotaName = "Exchange2007.IsConsumer", QuotaOrder = 1, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 369, GroupId = 12, QuotaDescription = "Enable Plans Editing", QuotaName = "Exchange2007.EnablePlansEditing", QuotaOrder = 23, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 370, GroupId = 41, PerOrganization = 1, QuotaDescription = "Users", QuotaName = "Lync.Users", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 371, GroupId = 41, QuotaDescription = "Allow Federation", QuotaName = "Lync.Federation", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 372, GroupId = 41, QuotaDescription = "Allow Conferencing", QuotaName = "Lync.Conferencing", QuotaOrder = 3, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 373, GroupId = 41, QuotaDescription = "Maximum Conference Particiapants", QuotaName = "Lync.MaxParticipants", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 374, GroupId = 41, QuotaDescription = "Allow Video in Conference", QuotaName = "Lync.AllowVideo", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 375, GroupId = 41, QuotaDescription = "Allow EnterpriseVoice", QuotaName = "Lync.EnterpriseVoice", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 376, GroupId = 41, QuotaDescription = "Number of Enterprise Voice Users", QuotaName = "Lync.EVUsers", QuotaOrder = 7, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 377, GroupId = 41, QuotaDescription = "Allow National Calls", QuotaName = "Lync.EVNational", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 378, GroupId = 41, QuotaDescription = "Allow Mobile Calls", QuotaName = "Lync.EVMobile", QuotaOrder = 9, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 379, GroupId = 41, QuotaDescription = "Allow International Calls", QuotaName = "Lync.EVInternational", QuotaOrder = 10, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 380, GroupId = 41, QuotaDescription = "Enable Plans Editing", QuotaName = "Lync.EnablePlansEditing", QuotaOrder = 11, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 381, GroupId = 41, QuotaDescription = "Phone Numbers", QuotaName = "Lync.PhoneNumbers", QuotaOrder = 12, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 400, GroupId = 20, QuotaDescription = "Use shared SSL Root", QuotaName = "HostedSharePoint.UseSharedSSL", QuotaOrder = 3, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 409, GroupId = 1, QuotaDescription = "Not allow Tenants to Delete Top Level Domains", QuotaName = "OS.NotAllowTenantDeleteDomains", QuotaOrder = 13, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 410, GroupId = 1, QuotaDescription = "Not allow Tenants to Create Top Level Domains", QuotaName = "OS.NotAllowTenantCreateDomains", QuotaOrder = 12, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 411, GroupId = 2, QuotaDescription = "Application Pools Restart", QuotaName = "Web.AppPoolsRestart", QuotaOrder = 13, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 420, GroupId = 12, QuotaDescription = "Allow Litigation Hold", QuotaName = "Exchange2007.AllowLitigationHold", QuotaOrder = 24, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 421, GroupId = 12, PerOrganization = 1, QuotaDescription = "Recoverable Items Space", QuotaName = "Exchange2007.RecoverableItemsSpace", QuotaOrder = 25,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 422, GroupId = 12, QuotaDescription = "Disclaimers Allowed", QuotaName = "Exchange2007.DisclaimersAllowed", QuotaOrder = 26, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 423, GroupId = 13, PerOrganization = 1, QuotaDescription = "Security Groups", QuotaName = "HostedSolution.SecurityGroups", QuotaOrder = 5,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 424, GroupId = 12, QuotaDescription = "Allow Retention Policy", QuotaName = "Exchange2013.AllowRetentionPolicy", QuotaOrder = 27, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 425, GroupId = 12, PerOrganization = 1, QuotaDescription = "Archiving storage, MB", QuotaName = "Exchange2013.ArchivingStorage", QuotaOrder = 29,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 426, GroupId = 12, PerOrganization = 1, QuotaDescription = "Archiving Mailboxes per Organization", QuotaName = "Exchange2013.ArchivingMailboxes", QuotaOrder = 28,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 428, GroupId = 12, PerOrganization = 1, QuotaDescription = "Resource Mailboxes per Organization", QuotaName = "Exchange2013.ResourceMailboxes", QuotaOrder = 31,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 429, GroupId = 12, PerOrganization = 1, QuotaDescription = "Shared Mailboxes per Organization", QuotaName = "Exchange2013.SharedMailboxes", QuotaOrder = 30,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 430, GroupId = 44, PerOrganization = 1, QuotaDescription = "Disk Storage Space (Mb)", QuotaName = "EnterpriseStorage.DiskStorageSpace", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 431, GroupId = 44, PerOrganization = 1, QuotaDescription = "Number of Root Folders", QuotaName = "EnterpriseStorage.Folders", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 447, GroupId = 61, QuotaDescription = "Enable Spam Filter", QuotaName = "Filters.Enable", QuotaOrder = 1, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 448, GroupId = 61, QuotaDescription = "Enable Per-Mailbox Login", QuotaName = "Filters.EnableEmailUsers", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 450, GroupId = 45, PerOrganization = 1, QuotaDescription = "Remote Desktop Users", QuotaName = "RDS.Users", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 451, GroupId = 45, PerOrganization = 1, QuotaDescription = "Remote Desktop Servers", QuotaName = "RDS.Servers", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 452, GroupId = 45, QuotaDescription = "Disable user from adding server", QuotaName = "RDS.DisableUserAddServer", QuotaOrder = 3, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 453, GroupId = 45, QuotaDescription = "Disable user from removing server", QuotaName = "RDS.DisableUserDeleteServer", QuotaOrder = 3, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 460, GroupId = 21, QuotaDescription = "Max Database Size, MB", QuotaName = "HostedCRM.MaxDatabaseSize", QuotaOrder = 5, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 461, GroupId = 21, PerOrganization = 1, QuotaDescription = "Limited licenses per organization", QuotaName = "HostedCRM.LimitedUsers", QuotaOrder = 3,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 462, GroupId = 21, PerOrganization = 1, QuotaDescription = "ESS licenses per organization", QuotaName = "HostedCRM.ESSUsers", QuotaOrder = 4,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 463, GroupId = 24, QuotaDescription = "CRM Organization", QuotaName = "HostedCRM2013.Organization", QuotaOrder = 1, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 464, GroupId = 24, QuotaDescription = "Max Database Size, MB", QuotaName = "HostedCRM2013.MaxDatabaseSize", QuotaOrder = 5, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 465, GroupId = 24, PerOrganization = 1, QuotaDescription = "Essential licenses per organization", QuotaName = "HostedCRM2013.EssentialUsers", QuotaOrder = 2,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 466, GroupId = 24, PerOrganization = 1, QuotaDescription = "Basic licenses per organization", QuotaName = "HostedCRM2013.BasicUsers", QuotaOrder = 3,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 467, GroupId = 24, PerOrganization = 1, QuotaDescription = "Professional licenses per organization", QuotaName = "HostedCRM2013.ProfessionalUsers", QuotaOrder = 4,
				QuotaTypeId = 3, ServiceQuota = false },
			new Quota() { QuotaId = 468, GroupId = 45, QuotaDescription = "Use Drive Maps", QuotaName = "EnterpriseStorage.DriveMaps", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 470, GroupId = 46, ItemTypeId = 39, QuotaDescription = "Databases", QuotaName = "MsSQL2014.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 471, GroupId = 46, ItemTypeId = 40, QuotaDescription = "Users", QuotaName = "MsSQL2014.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 472, GroupId = 46, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2014.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 473, GroupId = 46, QuotaDescription = "Database Backups", QuotaName = "MsSQL2014.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 474, GroupId = 46, QuotaDescription = "Database Restores", QuotaName = "MsSQL2014.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 475, GroupId = 46, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2014.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 476, GroupId = 46, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2014.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 491, GroupId = 45, PerOrganization = 1, QuotaDescription = "Remote Desktop Servers", QuotaName = "RDS.Collections", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 495, GroupId = 13, PerOrganization = 1, QuotaDescription = "Deleted Users", QuotaName = "HostedSolution.DeletedUsers", QuotaOrder = 6,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 496, GroupId = 13, PerOrganization = 1, QuotaDescription = "Deleted Users Backup Storage Space, Mb", QuotaName = "HostedSolution.DeletedUsersBackupStorageSpace", QuotaOrder = 6,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 550, GroupId = 73, ItemTypeId = 204, PerOrganization = 1, QuotaDescription = "SharePoint Site Collections", QuotaName = "HostedSharePointEnterprise.Sites",
				QuotaOrder = 1, QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 551, GroupId = 73, QuotaDescription = "Max site storage, MB", QuotaName = "HostedSharePointEnterprise.MaxStorage", QuotaOrder = 2, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 552, GroupId = 73, QuotaDescription = "Use shared SSL Root", QuotaName = "HostedSharePointEnterprise.UseSharedSSL", QuotaOrder = 3, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 553, GroupId = 33, ItemTypeId = 41, QuotaDescription = "Number of VPS", QuotaName = "VPS2012.ServersNumber", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 554, GroupId = 33, QuotaDescription = "Allow user to create VPS", QuotaName = "VPS2012.ManagingAllowed", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 555, GroupId = 33, QuotaDescription = "Number of CPU cores", QuotaName = "VPS2012.CpuNumber", QuotaOrder = 3, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 556, GroupId = 33, QuotaDescription = "Boot from CD allowed", QuotaName = "VPS2012.BootCdAllowed", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 557, GroupId = 33, QuotaDescription = "Boot from CD", QuotaName = "VPS2012.BootCdEnabled", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 558, GroupId = 33, QuotaDescription = "RAM size, MB", QuotaName = "VPS2012.Ram", QuotaOrder = 4, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 559, GroupId = 33, QuotaDescription = "Hard Drive size, GB", QuotaName = "VPS2012.Hdd", QuotaOrder = 5, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 560, GroupId = 33, QuotaDescription = "DVD drive", QuotaName = "VPS2012.DvdEnabled", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 561, GroupId = 33, QuotaDescription = "External Network", QuotaName = "VPS2012.ExternalNetworkEnabled", QuotaOrder = 10, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 562, GroupId = 33, QuotaDescription = "Number of External IP addresses", QuotaName = "VPS2012.ExternalIPAddressesNumber", QuotaOrder = 11, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 563, GroupId = 33, QuotaDescription = "Private Network", QuotaName = "VPS2012.PrivateNetworkEnabled", QuotaOrder = 13, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 564, GroupId = 33, QuotaDescription = "Number of Private IP addresses per VPS", QuotaName = "VPS2012.PrivateIPAddressesNumber", QuotaOrder = 14, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 565, GroupId = 33, QuotaDescription = "Number of Snaphots", QuotaName = "VPS2012.SnapshotsNumber", QuotaOrder = 9, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 566, GroupId = 33, QuotaDescription = "Allow user to Start, Turn off and Shutdown VPS", QuotaName = "VPS2012.StartShutdownAllowed", QuotaOrder = 15, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 567, GroupId = 33, QuotaDescription = "Allow user to Pause, Resume VPS", QuotaName = "VPS2012.PauseResumeAllowed", QuotaOrder = 16, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 568, GroupId = 33, QuotaDescription = "Allow user to Reboot VPS", QuotaName = "VPS2012.RebootAllowed", QuotaOrder = 17, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 569, GroupId = 33, QuotaDescription = "Allow user to Reset VPS", QuotaName = "VPS2012.ResetAlowed", QuotaOrder = 18, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 570, GroupId = 33, QuotaDescription = "Allow user to Re-install VPS", QuotaName = "VPS2012.ReinstallAllowed", QuotaOrder = 19, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 571, GroupId = 33, QuotaDescription = "Monthly bandwidth, GB", QuotaName = "VPS2012.Bandwidth", QuotaOrder = 12, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 572, GroupId = 33, QuotaDescription = "Allow user to Replication", QuotaName = "VPS2012.ReplicationEnabled", QuotaOrder = 20, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 573, GroupId = 50, ItemTypeId = 202, QuotaDescription = "Databases", QuotaName = "MariaDB.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 574, GroupId = 50, ItemTypeId = 203, QuotaDescription = "Users", QuotaName = "MariaDB.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 575, GroupId = 50, QuotaDescription = "Max Database Size", QuotaName = "MariaDB.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 576, GroupId = 50, QuotaDescription = "Database Backups", QuotaName = "MariaDB.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 577, GroupId = 50, QuotaDescription = "Database Restores", QuotaName = "MariaDB.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 578, GroupId = 50, QuotaDescription = "Database Truncate", QuotaName = "MariaDB.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 579, GroupId = 50, QuotaDescription = "Max Log Size", QuotaName = "MariaDB.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 581, GroupId = 52, QuotaDescription = "Phone Numbers", QuotaName = "SfB.PhoneNumbers", QuotaOrder = 12, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 582, GroupId = 52, PerOrganization = 1, QuotaDescription = "Users", QuotaName = "SfB.Users", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 583, GroupId = 52, QuotaDescription = "Allow Federation", QuotaName = "SfB.Federation", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 584, GroupId = 52, QuotaDescription = "Allow Conferencing", QuotaName = "SfB.Conferencing", QuotaOrder = 3, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 585, GroupId = 52, QuotaDescription = "Maximum Conference Particiapants", QuotaName = "SfB.MaxParticipants", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 586, GroupId = 52, QuotaDescription = "Allow Video in Conference", QuotaName = "SfB.AllowVideo", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 587, GroupId = 52, QuotaDescription = "Allow EnterpriseVoice", QuotaName = "SfB.EnterpriseVoice", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 588, GroupId = 52, QuotaDescription = "Number of Enterprise Voice Users", QuotaName = "SfB.EVUsers", QuotaOrder = 7, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 589, GroupId = 52, QuotaDescription = "Allow National Calls", QuotaName = "SfB.EVNational", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 590, GroupId = 52, QuotaDescription = "Allow Mobile Calls", QuotaName = "SfB.EVMobile", QuotaOrder = 9, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 591, GroupId = 52, QuotaDescription = "Allow International Calls", QuotaName = "SfB.EVInternational", QuotaOrder = 10, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 592, GroupId = 52, QuotaDescription = "Enable Plans Editing", QuotaName = "SfB.EnablePlansEditing", QuotaOrder = 11, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 673, GroupId = 167, ItemTypeId = 41, QuotaDescription = "Number of VPS", QuotaName = "PROXMOX.ServersNumber", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 674, GroupId = 167, QuotaDescription = "Allow user to create VPS", QuotaName = "PROXMOX.ManagingAllowed", QuotaOrder = 2, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 675, GroupId = 167, QuotaDescription = "Number of CPU cores", QuotaName = "PROXMOX.CpuNumber", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 676, GroupId = 167, QuotaDescription = "Boot from CD allowed", QuotaName = "PROXMOX.BootCdAllowed", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 677, GroupId = 167, QuotaDescription = "Boot from CD", QuotaName = "PROXMOX.BootCdEnabled", QuotaOrder = 8, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 678, GroupId = 167, QuotaDescription = "RAM size, MB", QuotaName = "PROXMOX.Ram", QuotaOrder = 4, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 679, GroupId = 167, QuotaDescription = "Hard Drive size, GB", QuotaName = "PROXMOX.Hdd", QuotaOrder = 5, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 680, GroupId = 167, QuotaDescription = "DVD drive", QuotaName = "PROXMOX.DvdEnabled", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 681, GroupId = 167, QuotaDescription = "External Network", QuotaName = "PROXMOX.ExternalNetworkEnabled", QuotaOrder = 10, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 682, GroupId = 167, QuotaDescription = "Number of External IP addresses", QuotaName = "PROXMOX.ExternalIPAddressesNumber", QuotaOrder = 11, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 683, GroupId = 167, QuotaDescription = "Private Network", QuotaName = "PROXMOX.PrivateNetworkEnabled", QuotaOrder = 13, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 684, GroupId = 167, QuotaDescription = "Number of Private IP addresses per VPS", QuotaName = "PROXMOX.PrivateIPAddressesNumber", QuotaOrder = 14, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 685, GroupId = 167, QuotaDescription = "Number of Snaphots", QuotaName = "PROXMOX.SnapshotsNumber", QuotaOrder = 9, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 686, GroupId = 167, QuotaDescription = "Allow user to Start, Turn off and Shutdown VPS", QuotaName = "PROXMOX.StartShutdownAllowed", QuotaOrder = 15, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 687, GroupId = 167, QuotaDescription = "Allow user to Pause, Resume VPS", QuotaName = "PROXMOX.PauseResumeAllowed", QuotaOrder = 16, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 688, GroupId = 167, QuotaDescription = "Allow user to Reboot VPS", QuotaName = "PROXMOX.RebootAllowed", QuotaOrder = 17, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 689, GroupId = 167, QuotaDescription = "Allow user to Reset VPS", QuotaName = "PROXMOX.ResetAlowed", QuotaOrder = 18, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 690, GroupId = 167, QuotaDescription = "Allow user to Re-install VPS", QuotaName = "PROXMOX.ReinstallAllowed", QuotaOrder = 19, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 691, GroupId = 167, QuotaDescription = "Monthly bandwidth, GB", QuotaName = "PROXMOX.Bandwidth", QuotaOrder = 12, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 692, GroupId = 167, QuotaDescription = "Allow user to Replication", QuotaName = "PROXMOX.ReplicationEnabled", QuotaOrder = 20, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 701, GroupId = 71, ItemTypeId = 71, QuotaDescription = "Databases", QuotaName = "MsSQL2016.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 702, GroupId = 71, ItemTypeId = 72, QuotaDescription = "Users", QuotaName = "MsSQL2016.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 703, GroupId = 71, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2016.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 704, GroupId = 71, QuotaDescription = "Database Backups", QuotaName = "MsSQL2016.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 705, GroupId = 71, QuotaDescription = "Database Restores", QuotaName = "MsSQL2016.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 706, GroupId = 71, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2016.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 707, GroupId = 71, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2016.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 711, GroupId = 72, ItemTypeId = 73, QuotaDescription = "Databases", QuotaName = "MsSQL2017.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 712, GroupId = 72, ItemTypeId = 74, QuotaDescription = "Users", QuotaName = "MsSQL2017.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 713, GroupId = 72, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2017.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 714, GroupId = 72, QuotaDescription = "Database Backups", QuotaName = "MsSQL2017.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 715, GroupId = 72, QuotaDescription = "Database Restores", QuotaName = "MsSQL2017.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 716, GroupId = 72, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2017.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 717, GroupId = 72, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2017.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 721, GroupId = 74, ItemTypeId = 77, QuotaDescription = "Databases", QuotaName = "MsSQL2019.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 722, GroupId = 74, ItemTypeId = 78, QuotaDescription = "Users", QuotaName = "MsSQL2019.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 723, GroupId = 74, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2019.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 724, GroupId = 74, QuotaDescription = "Database Backups", QuotaName = "MsSQL2019.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 725, GroupId = 74, QuotaDescription = "Database Restores", QuotaName = "MsSQL2019.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 726, GroupId = 74, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2019.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 727, GroupId = 74, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2019.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 728, GroupId = 33, QuotaDescription = "Number of Private Network VLANs", QuotaName = "VPS2012.PrivateVLANsNumber", QuotaOrder = 14, QuotaTypeId = 2,
				ServiceQuota = false },
			new Quota() { QuotaId = 729, GroupId = 12, QuotaDescription = "Automatic Replies via SolidCP Allowed", QuotaName = "Exchange2013.AutoReply", QuotaOrder = 32, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 730, GroupId = 33, QuotaDescription = "Additional Hard Drives per VPS", QuotaName = "VPS2012.AdditionalVhdCount", QuotaOrder = 6, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 731, GroupId = 12, PerOrganization = 1, QuotaDescription = "Journaling Mailboxes per Organization", QuotaName = "Exchange2013.JournalingMailboxes", QuotaOrder = 31,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 732, GroupId = 75, ItemTypeId = 79, QuotaDescription = "Databases", QuotaName = "MsSQL2022.Databases", QuotaOrder = 1,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 733, GroupId = 75, ItemTypeId = 80, QuotaDescription = "Users", QuotaName = "MsSQL2022.Users", QuotaOrder = 2,
				QuotaTypeId = 2, ServiceQuota = false },
			new Quota() { QuotaId = 734, GroupId = 75, QuotaDescription = "Max Database Size", QuotaName = "MsSQL2022.MaxDatabaseSize", QuotaOrder = 3, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 735, GroupId = 75, QuotaDescription = "Database Backups", QuotaName = "MsSQL2022.Backup", QuotaOrder = 5, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 736, GroupId = 75, QuotaDescription = "Database Restores", QuotaName = "MsSQL2022.Restore", QuotaOrder = 6, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 737, GroupId = 75, QuotaDescription = "Database Truncate", QuotaName = "MsSQL2022.Truncate", QuotaOrder = 7, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 738, GroupId = 75, QuotaDescription = "Max Log Size", QuotaName = "MsSQL2022.MaxLogSize", QuotaOrder = 4, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 750, GroupId = 33, QuotaDescription = "DMZ Network", QuotaName = "VPS2012.DMZNetworkEnabled", QuotaOrder = 22, QuotaTypeId = 1,
				ServiceQuota = false },
			new Quota() { QuotaId = 751, GroupId = 33, QuotaDescription = "Number of DMZ IP addresses per VPS", QuotaName = "VPS2012.DMZIPAddressesNumber", QuotaOrder = 23, QuotaTypeId = 3,
				ServiceQuota = false },
			new Quota() { QuotaId = 752, GroupId = 33, QuotaDescription = "Number of DMZ Network VLANs", QuotaName = "VPS2012.DMZVLANsNumber", QuotaOrder = 24, QuotaTypeId = 2,
				ServiceQuota = false }
		});
		#endregion
	}
}