#!/bin/sh
echo "===================================================================="
echo "run 'sudo solidcp-installer' to complete the installation of SolidCP"
echo "===================================================================="
