// This file is auto generated, do not edit.
using System;
using System.Collections.Generic;
using SolidCP.EnterpriseServer.Data.Configuration;
using SolidCP.EnterpriseServer.Data.Entities;
using SolidCP.EnterpriseServer.Data.Extensions;
#if NetCore
using Microsoft.EntityFrameworkCore;
#endif
#if NetFX
using System.Data.Entity;
#endif

namespace SolidCP.EnterpriseServer.Data.Configuration;

public partial class AuditLogTaskConfiguration: EntityTypeConfiguration<AuditLogTask>
{
    public override void Configure() {
        HasKey(e => new { e.SourceName, e.TaskName }).HasName("PK_LogActions");

        #region Seed Data
        HasData(() => new AuditLogTask[] {
            new AuditLogTask() { SourceName = "APP_INSTALLER", TaskName = "INSTALL_APPLICATION", TaskDescription = "Install application" },
            new AuditLogTask() { SourceName = "AUTO_DISCOVERY", TaskName = "IS_INSTALLED", TaskDescription = "Is installed" },
            new AuditLogTask() { SourceName = "BACKUP", TaskName = "BACKUP", TaskDescription = "Backup" },
            new AuditLogTask() { SourceName = "BACKUP", TaskName = "RESTORE", TaskDescription = "Restore" },
            new AuditLogTask() { SourceName = "DNS_ZONE", TaskName = "ADD_RECORD", TaskDescription = "Add record" },
            new AuditLogTask() { SourceName = "DNS_ZONE", TaskName = "DELETE_RECORD", TaskDescription = "Delete record" },
            new AuditLogTask() { SourceName = "DNS_ZONE", TaskName = "UPDATE_RECORD", TaskDescription = "Update record" },
            new AuditLogTask() { SourceName = "DOMAIN", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "DOMAIN", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "DOMAIN", TaskName = "ENABLE_DNS", TaskDescription = "Enable DNS" },
            new AuditLogTask() { SourceName = "DOMAIN", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "ENTERPRISE_STORAGE", TaskName = "CREATE_FOLDER", TaskDescription = "Create folder" },
            new AuditLogTask() { SourceName = "ENTERPRISE_STORAGE", TaskName = "CREATE_MAPPED_DRIVE", TaskDescription = "Create mapped drive" },
            new AuditLogTask() { SourceName = "ENTERPRISE_STORAGE", TaskName = "DELETE_FOLDER", TaskDescription = "Delete folder" },
            new AuditLogTask() { SourceName = "ENTERPRISE_STORAGE", TaskName = "DELETE_MAPPED_DRIVE", TaskDescription = "Delete mapped drive" },
            new AuditLogTask() { SourceName = "ENTERPRISE_STORAGE", TaskName = "GET_ORG_STATS", TaskDescription = "Get organization statistics" },
            new AuditLogTask() { SourceName = "ENTERPRISE_STORAGE", TaskName = "SET_ENTERPRISE_FOLDER_GENERAL_SETTINGS", TaskDescription = "Set enterprise folder general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "ADD_DISTR_LIST_ADDRESS", TaskDescription = "Add distribution list e-mail address" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "ADD_DOMAIN", TaskDescription = "Add organization domain" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "ADD_EXCHANGE_EXCHANGEDISCLAIMER", TaskDescription = "Add Exchange disclaimer" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "ADD_EXCHANGE_MAILBOXPLAN_RETENTIONPOLICY_ARCHIVING", TaskDescription = "Add Exchange archiving retention policy" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "ADD_EXCHANGE_RETENTIONPOLICYTAG", TaskDescription = "Add Exchange retention policy tag" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "ADD_MAILBOX_ADDRESS", TaskDescription = "Add mailbox e-mail address" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "ADD_PUBLIC_FOLDER_ADDRESS", TaskDescription = "Add public folder e-mail address" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "CALCULATE_DISKSPACE", TaskDescription = "Calculate organization disk space" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "CREATE_CONTACT", TaskDescription = "Create contact" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "CREATE_DISTR_LIST", TaskDescription = "Create distribution list" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "CREATE_MAILBOX", TaskDescription = "Create mailbox" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "CREATE_ORG", TaskDescription = "Create organization" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "CREATE_PUBLIC_FOLDER", TaskDescription = "Create public folder" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_CONTACT", TaskDescription = "Delete contact" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_DISTR_LIST", TaskDescription = "Delete distribution list" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_DISTR_LIST_ADDRESSES", TaskDescription = "Delete distribution list e-mail addresses" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_DOMAIN", TaskDescription = "Delete organization domain" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_EXCHANGE_MAILBOXPLAN_RETENTIONPOLICY_ARCHIV", TaskDescription = "Delete Exchange archiving retention policy" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_EXCHANGE_RETENTIONPOLICYTAG", TaskDescription = "Delete Exchange retention policy tag" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_MAILBOX", TaskDescription = "Delete mailbox" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_MAILBOX_ADDRESSES", TaskDescription = "Delete mailbox e-mail addresses" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_ORG", TaskDescription = "Delete organization" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_PUBLIC_FOLDER", TaskDescription = "Delete public folder" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DELETE_PUBLIC_FOLDER_ADDRESSES", TaskDescription = "Delete public folder e-mail addresses" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DISABLE_MAIL_PUBLIC_FOLDER", TaskDescription = "Disable mail public folder" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "DISABLE_MAILBOX", TaskDescription = "Disable Mailbox" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "ENABLE_MAIL_PUBLIC_FOLDER", TaskDescription = "Enable mail public folder" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_ACTIVESYNC_POLICY", TaskDescription = "Get Activesync policy" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_CONTACT_GENERAL", TaskDescription = "Get contact general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_CONTACT_MAILFLOW", TaskDescription = "Get contact mail flow settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_DISTR_LIST_ADDRESSES", TaskDescription = "Get distribution list e-mail addresses" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_DISTR_LIST_BYMEMBER", TaskDescription = "Get distributions list by member" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_DISTR_LIST_GENERAL", TaskDescription = "Get distribution list general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_DISTR_LIST_MAILFLOW", TaskDescription = "Get distribution list mail flow settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_DISTRIBUTION_LIST_RESULT", TaskDescription = "Get distributions list result" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_EXCHANGE_ACCOUNTDISCLAIMERID", TaskDescription = "Get Exchange account disclaimer id" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_EXCHANGE_EXCHANGEDISCLAIMER", TaskDescription = "Get Exchange disclaimer" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_EXCHANGE_MAILBOXPLAN", TaskDescription = "Get Exchange Mailbox plan" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_EXCHANGE_MAILBOXPLANS", TaskDescription = "Get Exchange Mailbox plans" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_EXCHANGE_RETENTIONPOLICYTAG", TaskDescription = "Get Exchange retention policy tag" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_EXCHANGE_RETENTIONPOLICYTAGS", TaskDescription = "Get Exchange retention policy tags" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_FOLDERS_STATS", TaskDescription = "Get organization public folder statistics" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MAILBOX_ADDRESSES", TaskDescription = "Get mailbox e-mail addresses" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MAILBOX_ADVANCED", TaskDescription = "Get mailbox advanced settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MAILBOX_AUTOREPLY", TaskDescription = "Get Mailbox autoreply" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MAILBOX_GENERAL", TaskDescription = "Get mailbox general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MAILBOX_MAILFLOW", TaskDescription = "Get mailbox mail flow settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MAILBOX_PERMISSIONS", TaskDescription = "Get Mailbox permissions" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MAILBOX_STATS", TaskDescription = "Get Mailbox statistics" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MAILBOXES_STATS", TaskDescription = "Get organization mailboxes statistics" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_MOBILE_DEVICES", TaskDescription = "Get mobile devices" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_ORG_LIMITS", TaskDescription = "Get organization storage limits" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_ORG_STATS", TaskDescription = "Get organization statistics" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_PICTURE", TaskDescription = "Get picture" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_PUBLIC_FOLDER_ADDRESSES", TaskDescription = "Get public folder e-mail addresses" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_PUBLIC_FOLDER_GENERAL", TaskDescription = "Get public folder general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_PUBLIC_FOLDER_MAILFLOW", TaskDescription = "Get public folder mail flow settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "GET_RESOURCE_MAILBOX", TaskDescription = "Get resource Mailbox settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "SET_EXCHANGE_ACCOUNTDISCLAIMERID", TaskDescription = "Set exchange account disclaimer id" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "SET_EXCHANGE_MAILBOXPLAN", TaskDescription = "Set exchange Mailbox plan" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "SET_MAILBOXPLAN_RETENTIONPOLICY_ARCHIVING", TaskDescription = "Set Mailbox plan retention policy archiving" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "SET_ORG_LIMITS", TaskDescription = "Update organization storage limits" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "SET_PRIMARY_DISTR_LIST_ADDRESS", TaskDescription = "Set distribution list primary e-mail address" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "SET_PRIMARY_MAILBOX_ADDRESS", TaskDescription = "Set mailbox primary e-mail address" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "SET_PRIMARY_PUBLIC_FOLDER_ADDRESS", TaskDescription = "Set public folder primary e-mail address" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_CONTACT_GENERAL", TaskDescription = "Update contact general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_CONTACT_MAILFLOW", TaskDescription = "Update contact mail flow settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_DISTR_LIST_GENERAL", TaskDescription = "Update distribution list general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_DISTR_LIST_MAILFLOW", TaskDescription = "Update distribution list mail flow settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_EXCHANGE_RETENTIONPOLICYTAG", TaskDescription = "Update Exchange retention policy tag" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_MAILBOX_ADVANCED", TaskDescription = "Update mailbox advanced settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_MAILBOX_AUTOREPLY", TaskDescription = "Update Mailbox autoreply" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_MAILBOX_GENERAL", TaskDescription = "Update mailbox general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_MAILBOX_MAILFLOW", TaskDescription = "Update mailbox mail flow settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_PUBLIC_FOLDER_GENERAL", TaskDescription = "Update public folder general settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_PUBLIC_FOLDER_MAILFLOW", TaskDescription = "Update public folder mail flow settings" },
            new AuditLogTask() { SourceName = "EXCHANGE", TaskName = "UPDATE_RESOURCE_MAILBOX", TaskDescription = "Update resource Mailbox settings" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "COPY_FILES", TaskDescription = "Copy files" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "CREATE_ACCESS_DATABASE", TaskDescription = "Create MS Access database" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "CREATE_FILE", TaskDescription = "Create file" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "CREATE_FOLDER", TaskDescription = "Create folder" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "DELETE_FILES", TaskDescription = "Delete files" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "MOVE_FILES", TaskDescription = "Move files" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "RENAME_FILE", TaskDescription = "Rename file" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "SET_PERMISSIONS",  },
            new AuditLogTask() { SourceName = "FILES", TaskName = "UNZIP_FILES", TaskDescription = "Unzip files" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "UPDATE_BINARY_CONTENT", TaskDescription = "Update file binary content" },
            new AuditLogTask() { SourceName = "FILES", TaskName = "ZIP_FILES", TaskDescription = "Zip files" },
            new AuditLogTask() { SourceName = "FTP_ACCOUNT", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "FTP_ACCOUNT", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "FTP_ACCOUNT", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "GLOBAL_DNS", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "GLOBAL_DNS", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "GLOBAL_DNS", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "HOSTING_SPACE", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "HOSTING_SPACE_WR", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "IMPORT", TaskName = "IMPORT", TaskDescription = "Import" },
            new AuditLogTask() { SourceName = "IP_ADDRESS", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "IP_ADDRESS", TaskName = "ADD_RANGE", TaskDescription = "Add range" },
            new AuditLogTask() { SourceName = "IP_ADDRESS", TaskName = "ALLOCATE_PACKAGE_IP", TaskDescription = "Allocate package IP addresses" },
            new AuditLogTask() { SourceName = "IP_ADDRESS", TaskName = "DEALLOCATE_PACKAGE_IP", TaskDescription = "Deallocate package IP addresses" },
            new AuditLogTask() { SourceName = "IP_ADDRESS", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "IP_ADDRESS", TaskName = "DELETE_RANGE", TaskDescription = "Delete IP Addresses" },
            new AuditLogTask() { SourceName = "IP_ADDRESS", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "IP_ADDRESS", TaskName = "UPDATE_RANGE", TaskDescription = "Update IP Addresses" },
            new AuditLogTask() { SourceName = "MAIL_ACCOUNT", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "MAIL_ACCOUNT", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "MAIL_ACCOUNT", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "MAIL_DOMAIN", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "MAIL_DOMAIN", TaskName = "ADD_POINTER", TaskDescription = "Add pointer" },
            new AuditLogTask() { SourceName = "MAIL_DOMAIN", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "MAIL_DOMAIN", TaskName = "DELETE_POINTER", TaskDescription = "Update pointer" },
            new AuditLogTask() { SourceName = "MAIL_DOMAIN", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "MAIL_FORWARDING", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "MAIL_FORWARDING", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "MAIL_FORWARDING", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "MAIL_GROUP", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "MAIL_GROUP", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "MAIL_GROUP", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "MAIL_LIST", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "MAIL_LIST", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "MAIL_LIST", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "OCS", TaskName = "CREATE_OCS_USER", TaskDescription = "Create OCS user" },
            new AuditLogTask() { SourceName = "OCS", TaskName = "GET_OCS_USERS", TaskDescription = "Get OCS users" },
            new AuditLogTask() { SourceName = "OCS", TaskName = "GET_OCS_USERS_COUNT", TaskDescription = "Get OCS users count" },
            new AuditLogTask() { SourceName = "ODBC_DSN", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "ODBC_DSN", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "ODBC_DSN", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "CREATE_ORG", TaskDescription = "Create organization" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "CREATE_ORGANIZATION_ENTERPRISE_STORAGE", TaskDescription = "Create organization enterprise storage" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "CREATE_SECURITY_GROUP", TaskDescription = "Create security group" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "CREATE_USER", TaskDescription = "Create user" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "DELETE_ORG", TaskDescription = "Delete organization" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "DELETE_SECURITY_GROUP", TaskDescription = "Delete security group" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "GET_ORG_STATS", TaskDescription = "Get organization statistics" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "GET_SECURITY_GROUP_GENERAL", TaskDescription = "Get security group general settings" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "GET_SECURITY_GROUPS_BYMEMBER", TaskDescription = "Get security groups by member" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "GET_SUPPORT_SERVICE_LEVELS", TaskDescription = "Get support service levels" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "REMOVE_USER", TaskDescription = "Remove user" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "SEND_USER_PASSWORD_RESET_EMAIL_PINCODE", TaskDescription = "Send user password reset email pincode" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "SET_USER_PASSWORD", TaskDescription = "Set user password" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "SET_USER_USERPRINCIPALNAME", TaskDescription = "Set user principal name" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "UPDATE_PASSWORD_SETTINGS", TaskDescription = "Update password settings" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "UPDATE_SECURITY_GROUP_GENERAL", TaskDescription = "Update security group general settings" },
            new AuditLogTask() { SourceName = "ORGANIZATION", TaskName = "UPDATE_USER_GENERAL", TaskDescription = "Update user general settings" },
            new AuditLogTask() { SourceName = "REMOTE_DESKTOP_SERVICES", TaskName = "ADD_RDS_SERVER", TaskDescription = "Add RDS server" },
            new AuditLogTask() { SourceName = "REMOTE_DESKTOP_SERVICES", TaskName = "RESTART_RDS_SERVER", TaskDescription = "Restart RDS server" },
            new AuditLogTask() { SourceName = "REMOTE_DESKTOP_SERVICES", TaskName = "SET_RDS_SERVER_NEW_CONNECTIONS_ALLOWED", TaskDescription = "Set RDS new connection allowed" },
            new AuditLogTask() { SourceName = "SCHEDULER", TaskName = "RUN_SCHEDULE",  },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "ADD_SERVICE", TaskDescription = "Add service" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "CHANGE_WINDOWS_SERVICE_STATUS", TaskDescription = "Change Windows service status" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "CHECK_AVAILABILITY", TaskDescription = "Check availability" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "CLEAR_EVENT_LOG", TaskDescription = "Clear Windows event log" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "DELETE_SERVICE", TaskDescription = "Delete service" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "REBOOT", TaskDescription = "Reboot" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "RESET_TERMINAL_SESSION", TaskDescription = "Reset terminal session" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "TERMINATE_SYSTEM_PROCESS", TaskDescription = "Terminate system process" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "UPDATE_AD_PASSWORD", TaskDescription = "Update active directory password" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "UPDATE_PASSWORD", TaskDescription = "Update access password" },
            new AuditLogTask() { SourceName = "SERVER", TaskName = "UPDATE_SERVICE", TaskDescription = "Update service" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "ADD_GROUP", TaskDescription = "Add group" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "ADD_SITE", TaskDescription = "Add site" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "ADD_USER", TaskDescription = "Add user" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "BACKUP_SITE", TaskDescription = "Backup site" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "DELETE_GROUP", TaskDescription = "Delete group" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "DELETE_SITE", TaskDescription = "Delete site" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "DELETE_USER", TaskDescription = "Delete user" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "INSTALL_WEBPARTS", TaskDescription = "Install Web Parts package" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "RESTORE_SITE", TaskDescription = "Restore site" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "UNINSTALL_WEBPARTS", TaskDescription = "Uninstall Web Parts package" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "UPDATE_GROUP", TaskDescription = "Update group" },
            new AuditLogTask() { SourceName = "SHAREPOINT", TaskName = "UPDATE_USER", TaskDescription = "Update user" },
            new AuditLogTask() { SourceName = "SPACE", TaskName = "CALCULATE_DISKSPACE", TaskDescription = "Calculate disk space" },
            new AuditLogTask() { SourceName = "SPACE", TaskName = "CHANGE_ITEMS_STATUS", TaskDescription = "Change hosting items status" },
            new AuditLogTask() { SourceName = "SPACE", TaskName = "CHANGE_STATUS", TaskDescription = "Change hostng space status" },
            new AuditLogTask() { SourceName = "SPACE", TaskName = "DELETE", TaskDescription = "Delete hosting space" },
            new AuditLogTask() { SourceName = "SPACE", TaskName = "DELETE_ITEMS", TaskDescription = "Delete hosting items" },
            new AuditLogTask() { SourceName = "SQL_DATABASE", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "SQL_DATABASE", TaskName = "BACKUP", TaskDescription = "Backup" },
            new AuditLogTask() { SourceName = "SQL_DATABASE", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "SQL_DATABASE", TaskName = "RESTORE", TaskDescription = "Restore" },
            new AuditLogTask() { SourceName = "SQL_DATABASE", TaskName = "TRUNCATE", TaskDescription = "Truncate" },
            new AuditLogTask() { SourceName = "SQL_DATABASE", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "SQL_USER", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "SQL_USER", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "SQL_USER", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "STATS_SITE", TaskName = "ADD", TaskDescription = "Add statistics site" },
            new AuditLogTask() { SourceName = "STATS_SITE", TaskName = "DELETE", TaskDescription = "Delete statistics site" },
            new AuditLogTask() { SourceName = "STATS_SITE", TaskName = "UPDATE", TaskDescription = "Update statistics site" },
            new AuditLogTask() { SourceName = "STORAGE_SPACES", TaskName = "REMOVE_STORAGE_SPACE", TaskDescription = "Remove storage space" },
            new AuditLogTask() { SourceName = "STORAGE_SPACES", TaskName = "SAVE_STORAGE_SPACE", TaskDescription = "Save storage space" },
            new AuditLogTask() { SourceName = "STORAGE_SPACES", TaskName = "SAVE_STORAGE_SPACE_LEVEL", TaskDescription = "Save storage space level" },
            new AuditLogTask() { SourceName = "USER", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "USER", TaskName = "AUTHENTICATE", TaskDescription = "Authenticate" },
            new AuditLogTask() { SourceName = "USER", TaskName = "CHANGE_PASSWORD", TaskDescription = "Change password" },
            new AuditLogTask() { SourceName = "USER", TaskName = "CHANGE_PASSWORD_BY_USERNAME_PASSWORD", TaskDescription = "Change password by username/password" },
            new AuditLogTask() { SourceName = "USER", TaskName = "CHANGE_STATUS", TaskDescription = "Change status" },
            new AuditLogTask() { SourceName = "USER", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "USER", TaskName = "GET_BY_USERNAME_PASSWORD", TaskDescription = "Get by username/password" },
            new AuditLogTask() { SourceName = "USER", TaskName = "SEND_REMINDER", TaskDescription = "Send password reminder" },
            new AuditLogTask() { SourceName = "USER", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "USER", TaskName = "UPDATE_SETTINGS", TaskDescription = "Update settings" },
            new AuditLogTask() { SourceName = "VIRTUAL_SERVER", TaskName = "ADD_SERVICES", TaskDescription = "Add services" },
            new AuditLogTask() { SourceName = "VIRTUAL_SERVER", TaskName = "DELETE_SERVICES", TaskDescription = "Delete services" },
            new AuditLogTask() { SourceName = "VLAN", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "VLAN", TaskName = "ADD_RANGE", TaskDescription = "Add range" },
            new AuditLogTask() { SourceName = "VLAN", TaskName = "ALLOCATE_PACKAGE_VLAN", TaskDescription = "Allocate package VLAN" },
            new AuditLogTask() { SourceName = "VLAN", TaskName = "DEALLOCATE_PACKAGE_VLAN", TaskDescription = "Deallocate package VLAN" },
            new AuditLogTask() { SourceName = "VLAN", TaskName = "DELETE_RANGE", TaskDescription = "Delete range" },
            new AuditLogTask() { SourceName = "VLAN", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "ADD_EXTERNAL_IP", TaskDescription = "Add external IP" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "ADD_PRIVATE_IP", TaskDescription = "Add private IP" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "APPLY_SNAPSHOT", TaskDescription = "Apply VPS snapshot" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "CANCEL_JOB", TaskDescription = "Cancel Job" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "CHANGE_ADMIN_PASSWORD", TaskDescription = "Change administrator password" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "CHANGE_STATE", TaskDescription = "Change VPS state" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "CREATE", TaskDescription = "Create VPS" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "DELETE", TaskDescription = "Delete VPS" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "DELETE_EXTERNAL_IP", TaskDescription = "Delete external IP" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "DELETE_PRIVATE_IP", TaskDescription = "Delete private IP" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "DELETE_SNAPSHOT", TaskDescription = "Delete VPS snapshot" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "DELETE_SNAPSHOT_SUBTREE", TaskDescription = "Delete VPS snapshot subtree" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "EJECT_DVD_DISK", TaskDescription = "Eject DVD disk" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "INSERT_DVD_DISK", TaskDescription = "Insert DVD disk" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "REINSTALL", TaskDescription = "Re-install VPS" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "RENAME_SNAPSHOT", TaskDescription = "Rename VPS snapshot" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "SEND_SUMMARY_LETTER", TaskDescription = "Send VPS summary letter" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "SET_PRIMARY_EXTERNAL_IP", TaskDescription = "Set primary external IP" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "SET_PRIMARY_PRIVATE_IP", TaskDescription = "Set primary private IP" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "TAKE_SNAPSHOT", TaskDescription = "Take VPS snapshot" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "UPDATE_CONFIGURATION", TaskDescription = "Update VPS configuration" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "UPDATE_HOSTNAME", TaskDescription = "Update host name" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "UPDATE_IP", TaskDescription = "Update IP Address" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "UPDATE_PERMISSIONS", TaskDescription = "Update VPS permissions" },
            new AuditLogTask() { SourceName = "VPS", TaskName = "UPDATE_VDC_PERMISSIONS", TaskDescription = "Update space permissions" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "ADD_EXTERNAL_IP", TaskDescription = "Add external IP" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "ADD_PRIVATE_IP", TaskDescription = "Add private IP" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "APPLY_SNAPSHOT", TaskDescription = "Apply VM snapshot" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "CHANGE_ADMIN_PASSWORD", TaskDescription = "Change administrator password" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "CHANGE_STATE", TaskDescription = "Change VM state" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "CREATE", TaskDescription = "Create VM" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "DELETE", TaskDescription = "Delete VM" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "DELETE_EXTERNAL_IP", TaskDescription = "Delete external IP" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "DELETE_PRIVATE_IP", TaskDescription = "Delete private IP" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "DELETE_SNAPSHOT", TaskDescription = "Delete VM snapshot" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "DELETE_SNAPSHOT_SUBTREE", TaskDescription = "Delete VM snapshot subtree" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "EJECT_DVD_DISK", TaskDescription = "Eject DVD disk" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "INSERT_DVD_DISK", TaskDescription = "Insert DVD disk" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "REINSTALL", TaskDescription = "Reinstall VM" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "RENAME_SNAPSHOT", TaskDescription = "Rename VM snapshot" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "SET_PRIMARY_EXTERNAL_IP", TaskDescription = "Set primary external IP" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "SET_PRIMARY_PRIVATE_IP", TaskDescription = "Set primary private IP" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "TAKE_SNAPSHOT", TaskDescription = "Take VM snapshot" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "UPDATE_CONFIGURATION", TaskDescription = "Update VM configuration" },
            new AuditLogTask() { SourceName = "VPS2012", TaskName = "UPDATE_HOSTNAME", TaskDescription = "Update host name" },
            new AuditLogTask() { SourceName = "WAG_INSTALLER", TaskName = "GET_APP_PARAMS_TASK", TaskDescription = "Get application parameters" },
            new AuditLogTask() { SourceName = "WAG_INSTALLER", TaskName = "GET_GALLERY_APP_DETAILS_TASK", TaskDescription = "Get gallery application details" },
            new AuditLogTask() { SourceName = "WAG_INSTALLER", TaskName = "GET_GALLERY_APPS_TASK", TaskDescription = "Get gallery applications" },
            new AuditLogTask() { SourceName = "WAG_INSTALLER", TaskName = "GET_GALLERY_CATEGORIES_TASK", TaskDescription = "Get gallery categories" },
            new AuditLogTask() { SourceName = "WAG_INSTALLER", TaskName = "GET_SRV_GALLERY_APPS_TASK", TaskDescription = "Get server gallery applications" },
            new AuditLogTask() { SourceName = "WAG_INSTALLER", TaskName = "INSTALL_WEB_APP", TaskDescription = "Install Web application" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "ADD", TaskDescription = "Add" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "ADD_POINTER", TaskDescription = "Add domain pointer" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "ADD_SSL_FOLDER", TaskDescription = "Add shared SSL folder" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "ADD_VDIR", TaskDescription = "Add virtual directory" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "CHANGE_FP_PASSWORD", TaskDescription = "Change FrontPage account password" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "CHANGE_STATE", TaskDescription = "Change state" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "DELETE", TaskDescription = "Delete" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "DELETE_POINTER", TaskDescription = "Delete domain pointer" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "DELETE_SECURED_FOLDER", TaskDescription = "Delete secured folder" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "DELETE_SECURED_GROUP", TaskDescription = "Delete secured group" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "DELETE_SECURED_USER", TaskDescription = "Delete secured user" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "DELETE_SSL_FOLDER", TaskDescription = "Delete shared SSL folder" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "DELETE_VDIR", TaskDescription = "Delete virtual directory" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "GET_STATE", TaskDescription = "Get state" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "INSTALL_FP", TaskDescription = "Install FrontPage Extensions" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "INSTALL_SECURED_FOLDERS", TaskDescription = "Install secured folders" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "UNINSTALL_FP", TaskDescription = "Uninstall FrontPage Extensions" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "UNINSTALL_SECURED_FOLDERS", TaskDescription = "Uninstall secured folders" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "UPDATE", TaskDescription = "Update" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "UPDATE_SECURED_FOLDER", TaskDescription = "Add/update secured folder" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "UPDATE_SECURED_GROUP", TaskDescription = "Add/update secured group" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "UPDATE_SECURED_USER", TaskDescription = "Add/update secured user" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "UPDATE_SSL_FOLDER", TaskDescription = "Update shared SSL folder" },
            new AuditLogTask() { SourceName = "WEB_SITE", TaskName = "UPDATE_VDIR", TaskDescription = "Update virtual directory" }
        });
        #endregion

    }
}
