// This file is auto generated, do not edit.
using System;
using System.Collections.Generic;
using SolidCP.EnterpriseServer.Data.Configuration;
using SolidCP.EnterpriseServer.Data.Entities;
using SolidCP.EnterpriseServer.Data.Extensions;
#if NetCore
using Microsoft.EntityFrameworkCore;
#endif
#if NetFX
using System.Data.Entity;
#endif

namespace SolidCP.EnterpriseServer.Data.Configuration;

public partial class ServiceDefaultPropertyConfiguration: EntityTypeConfiguration<ServiceDefaultProperty>
{
    public override void Configure() {
        HasKey(e => new { e.ProviderId, e.PropertyName }).HasName("PK_ServiceDefaultProperties_1");

        HasOne(d => d.Provider).WithMany(p => p.ServiceDefaultProperties)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceDefaultProperties_Providers");

        #region Seed Data
        HasData(() => new ServiceDefaultProperty[] {
            new ServiceDefaultProperty() { ProviderId = 1, PropertyName = "UsersHome", PropertyValue = "%SYSTEMDRIVE%\\HostingSpaces" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "AspNet11Path", PropertyValue = "%SYSTEMROOT%\\Microsoft.NET\\Framework\\v1.1.4322\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "AspNet11Pool", PropertyValue = "ASP.NET V1.1" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "AspNet20Path", PropertyValue = "%SYSTEMROOT%\\Microsoft.NET\\Framework\\v2.0.50727\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "AspNet20Pool", PropertyValue = "ASP.NET V2.0" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "AspNet40Path", PropertyValue = "%SYSTEMROOT%\\Microsoft.NET\\Framework\\v4.0.30319\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "AspNet40Pool", PropertyValue = "ASP.NET V4.0" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "AspPath", PropertyValue = "%SYSTEMROOT%\\System32\\InetSrv\\asp.dll" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "CFFlashRemotingDirectory", PropertyValue = "C:\\ColdFusion9\\untime\\lib\\wsconfig\\1" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "CFScriptsDirectory", PropertyValue = "C:\\Inetpub\\wwwroot\\CFIDE" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "ColdFusionPath", PropertyValue = "C:\\ColdFusion9\\untime\\lib\\wsconfig\\jrun_iis6.dll" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "GalleryXmlFeedUrl", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "PerlPath", PropertyValue = "%SYSTEMDRIVE%\\Perl\\bin\\Perl.exe" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "Php4Path", PropertyValue = "%PROGRAMFILES%\\PHP\\php.exe" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "Php5Path", PropertyValue = "%PROGRAMFILES%\\PHP\\php-cgi.exe" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "ProtectedAccessFile", PropertyValue = ".htaccess" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "ProtectedFoldersFile", PropertyValue = ".htfolders" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "ProtectedGroupsFile", PropertyValue = ".htgroup" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "ProtectedUsersFile", PropertyValue = ".htpasswd" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "PythonPath", PropertyValue = "%SYSTEMDRIVE%\\Python\\python.exe" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "SecuredFoldersFilterPath", PropertyValue = "%SYSTEMROOT%\\System32\\InetSrv\\IISPasswordFilter.dll" },
            new ServiceDefaultProperty() { ProviderId = 2, PropertyName = "WebGroupName", PropertyValue = "SCPWebUsers" },
            new ServiceDefaultProperty() { ProviderId = 3, PropertyName = "FtpGroupName", PropertyValue = "SCPFtpUsers" },
            new ServiceDefaultProperty() { ProviderId = 3, PropertyName = "SiteId", PropertyValue = "MSFTPSVC/1" },
            new ServiceDefaultProperty() { ProviderId = 5, PropertyName = "DatabaseLocation", PropertyValue = "%SYSTEMDRIVE%\\SQL2000Databases\\[USER_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 5, PropertyName = "ExternalAddress", PropertyValue = "(local)" },
            new ServiceDefaultProperty() { ProviderId = 5, PropertyName = "InternalAddress", PropertyValue = "(local)" },
            new ServiceDefaultProperty() { ProviderId = 5, PropertyName = "SaLogin", PropertyValue = "sa" },
            new ServiceDefaultProperty() { ProviderId = 5, PropertyName = "SaPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 5, PropertyName = "UseDefaultDatabaseLocation", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 5, PropertyName = "UseTrustedConnection", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 6, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 6, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MySQL\\MySQL Server 4.1" },
            new ServiceDefaultProperty() { ProviderId = 6, PropertyName = "InternalAddress", PropertyValue = "localhost,3306" },
            new ServiceDefaultProperty() { ProviderId = 6, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 6, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 7, PropertyName = "ExpireLimit", PropertyValue = "1209600" },
            new ServiceDefaultProperty() { ProviderId = 7, PropertyName = "MinimumTTL", PropertyValue = "86400" },
            new ServiceDefaultProperty() { ProviderId = 7, PropertyName = "NameServers", PropertyValue = "ns1.yourdomain.com;ns2.yourdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 7, PropertyName = "RefreshInterval", PropertyValue = "3600" },
            new ServiceDefaultProperty() { ProviderId = 7, PropertyName = "ResponsiblePerson", PropertyValue = "hostmaster.[DOMAIN_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 7, PropertyName = "RetryDelay", PropertyValue = "600" },
            new ServiceDefaultProperty() { ProviderId = 8, PropertyName = "AwStatsFolder", PropertyValue = "%SYSTEMDRIVE%\\AWStats\\wwwroot\\cgi-bin" },
            new ServiceDefaultProperty() { ProviderId = 8, PropertyName = "BatchFileName", PropertyValue = "UpdateStats.bat" },
            new ServiceDefaultProperty() { ProviderId = 8, PropertyName = "BatchLineTemplate", PropertyValue = "%SYSTEMDRIVE%\\perl\\bin\\perl.exe awstats.pl config=[DOMAIN_NAME] -update" },
            new ServiceDefaultProperty() { ProviderId = 8, PropertyName = "ConfigFileName", PropertyValue = "awstats.[DOMAIN_NAME].conf" },
            new ServiceDefaultProperty() { ProviderId = 8, PropertyName = "ConfigFileTemplate", PropertyValue = 
@"LogFormat = ""%time2 %other %other %other %method %url %other %other %logname %host %other %ua %other %referer %other %code %other %other %bytesd %other %other""
LogSeparator = "" ""
DNSLookup = 2
DirCgi = ""/cgi-bin""
DirIcons = ""/icon""
AllowFullYearView=3
AllowToUpdateStatsFromBrowser = 0
UseFramesWhenCGI = 1
ShowFlagLinks = ""en fr de it nl es""
LogFile = ""[LOGS_FOLDER]\ex%YY-3%MM-3%DD-3.log""
DirData = ""%SYSTEMDRIVE%\AWStats\data""
SiteDomain = ""[DOMAIN_NAME]""
HostAliases = [DOMAIN_ALIASES]"
                 },
            new ServiceDefaultProperty() { ProviderId = 8, PropertyName = "StatisticsURL", PropertyValue = "http://127.0.0.1/AWStats/cgi-bin/awstats.pl?config=[domain_name]" },
            new ServiceDefaultProperty() { ProviderId = 9, PropertyName = "AdminLogin", PropertyValue = "Admin" },
            new ServiceDefaultProperty() { ProviderId = 9, PropertyName = "ExpireLimit", PropertyValue = "1209600" },
            new ServiceDefaultProperty() { ProviderId = 9, PropertyName = "MinimumTTL", PropertyValue = "86400" },
            new ServiceDefaultProperty() { ProviderId = 9, PropertyName = "NameServers", PropertyValue = "ns1.yourdomain.com;ns2.yourdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 9, PropertyName = "RefreshInterval", PropertyValue = "3600" },
            new ServiceDefaultProperty() { ProviderId = 9, PropertyName = "ResponsiblePerson", PropertyValue = "hostmaster.[DOMAIN_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 9, PropertyName = "RetryDelay", PropertyValue = "600" },
            new ServiceDefaultProperty() { ProviderId = 9, PropertyName = "SimpleDnsUrl", PropertyValue = "http://127.0.0.1:8053" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "LogDeleteDays", PropertyValue = "0" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "LogFormat", PropertyValue = "W3Cex" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "LogWildcard", PropertyValue = "*.log" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "Password", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "ServerID", PropertyValue = "1" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "SmarterLogDeleteMonths", PropertyValue = "0" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "SmarterLogsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterLogs" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "SmarterUrl", PropertyValue = "http://127.0.0.1:9999/services" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "StatisticsURL", PropertyValue = "http://127.0.0.1:9999/Login.aspx?txtSiteID=[site_id]&txtUser=[username]&txtPass=" +
                "[password]&shortcutLink=autologin" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "TimeZoneId", PropertyValue = "27" },
            new ServiceDefaultProperty() { ProviderId = 10, PropertyName = "Username", PropertyValue = "Admin" },
            new ServiceDefaultProperty() { ProviderId = 11, PropertyName = "AdminPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 11, PropertyName = "AdminUsername", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 11, PropertyName = "DomainsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterMail" },
            new ServiceDefaultProperty() { ProviderId = 11, PropertyName = "ServerIPAddress", PropertyValue = "127.0.0.1;127.0.0.1" },
            new ServiceDefaultProperty() { ProviderId = 11, PropertyName = "ServiceUrl", PropertyValue = "http://127.0.0.1:9998/services" },
            new ServiceDefaultProperty() { ProviderId = 12, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\Gene6 FTP Server" },
            new ServiceDefaultProperty() { ProviderId = 12, PropertyName = "LogsFolder", PropertyValue = "%PROGRAMFILES%\\Gene6 FTP Server\\Log" },
            new ServiceDefaultProperty() { ProviderId = 14, PropertyName = "AdminPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 14, PropertyName = "AdminUsername", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 14, PropertyName = "DomainsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterMail" },
            new ServiceDefaultProperty() { ProviderId = 14, PropertyName = "ServerIPAddress", PropertyValue = "127.0.0.1;127.0.0.1" },
            new ServiceDefaultProperty() { ProviderId = 14, PropertyName = "ServiceUrl", PropertyValue = "http://127.0.0.1:9998/services" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "BrowseMethod", PropertyValue = "POST" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "BrowseParameters", PropertyValue = 
@"ServerName=[SERVER]
Login=[USER]
Password=[PASSWORD]
Protocol=dbmssocn"
                 },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "BrowseURL", PropertyValue = "http://localhost/MLA/silentlogon.aspx" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "DatabaseLocation", PropertyValue = "%SYSTEMDRIVE%\\SQL2005Databases\\[USER_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "ExternalAddress", PropertyValue = "(local)" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "InternalAddress", PropertyValue = "(local)" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "SaLogin", PropertyValue = "sa" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "SaPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "UseDefaultDatabaseLocation", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 16, PropertyName = "UseTrustedConnection", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 17, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 17, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MySQL\\MySQL Server 5.0" },
            new ServiceDefaultProperty() { ProviderId = 17, PropertyName = "InternalAddress", PropertyValue = "localhost,3306" },
            new ServiceDefaultProperty() { ProviderId = 17, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 17, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 22, PropertyName = "AdminPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 22, PropertyName = "AdminUsername", PropertyValue = "Administrator" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "BindConfigPath", PropertyValue = "c:\\BIND\\dns\\etc\\
amed.conf" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "BindReloadBatch", PropertyValue = "c:\\BIND\\dns\\eload.bat" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "ExpireLimit", PropertyValue = "1209600" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "MinimumTTL", PropertyValue = "86400" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "NameServers", PropertyValue = "ns1.yourdomain.com;ns2.yourdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "RefreshInterval", PropertyValue = "3600" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "ResponsiblePerson", PropertyValue = "hostmaster.[DOMAIN_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "RetryDelay", PropertyValue = "600" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "ZoneFileNameTemplate", PropertyValue = "db.[domain_name].txt" },
            new ServiceDefaultProperty() { ProviderId = 24, PropertyName = "ZonesFolderPath", PropertyValue = "c:\\BIND\\dns\\zones" },
            new ServiceDefaultProperty() { ProviderId = 25, PropertyName = "DomainId", PropertyValue = "1" },
            new ServiceDefaultProperty() { ProviderId = 27, PropertyName = "KeepDeletedItemsDays", PropertyValue = "14" },
            new ServiceDefaultProperty() { ProviderId = 27, PropertyName = "KeepDeletedMailboxesDays", PropertyValue = "30" },
            new ServiceDefaultProperty() { ProviderId = 27, PropertyName = "MailboxDatabase", PropertyValue = "Hosted Exchange Database" },
            new ServiceDefaultProperty() { ProviderId = 27, PropertyName = "RootOU", PropertyValue = "SCP Hosting" },
            new ServiceDefaultProperty() { ProviderId = 27, PropertyName = "StorageGroup", PropertyValue = "Hosted Exchange Storage Group" },
            new ServiceDefaultProperty() { ProviderId = 27, PropertyName = "TempDomain", PropertyValue = "my-temp-domain.com" },
            new ServiceDefaultProperty() { ProviderId = 28, PropertyName = "AdminLogin", PropertyValue = "Admin" },
            new ServiceDefaultProperty() { ProviderId = 28, PropertyName = "ExpireLimit", PropertyValue = "1209600" },
            new ServiceDefaultProperty() { ProviderId = 28, PropertyName = "MinimumTTL", PropertyValue = "86400" },
            new ServiceDefaultProperty() { ProviderId = 28, PropertyName = "NameServers", PropertyValue = "ns1.yourdomain.com;ns2.yourdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 28, PropertyName = "RefreshInterval", PropertyValue = "3600" },
            new ServiceDefaultProperty() { ProviderId = 28, PropertyName = "ResponsiblePerson", PropertyValue = "hostmaster.[DOMAIN_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 28, PropertyName = "RetryDelay", PropertyValue = "600" },
            new ServiceDefaultProperty() { ProviderId = 28, PropertyName = "SimpleDnsUrl", PropertyValue = "http://127.0.0.1:8053" },
            new ServiceDefaultProperty() { ProviderId = 29, PropertyName = "AdminPassword", PropertyValue = " " },
            new ServiceDefaultProperty() { ProviderId = 29, PropertyName = "AdminUsername", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 29, PropertyName = "DomainsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterMail" },
            new ServiceDefaultProperty() { ProviderId = 29, PropertyName = "ServerIPAddress", PropertyValue = "127.0.0.1;127.0.0.1" },
            new ServiceDefaultProperty() { ProviderId = 29, PropertyName = "ServiceUrl", PropertyValue = "http://localhost:9998/services/" },
            new ServiceDefaultProperty() { ProviderId = 30, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 30, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MySQL\\MySQL Server 5.1" },
            new ServiceDefaultProperty() { ProviderId = 30, PropertyName = "InternalAddress", PropertyValue = "localhost,3306" },
            new ServiceDefaultProperty() { ProviderId = 30, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 30, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "LogDeleteDays", PropertyValue = "0" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "LogFormat", PropertyValue = "W3Cex" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "LogWildcard", PropertyValue = "*.log" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "Password", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "ServerID", PropertyValue = "1" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "SmarterLogDeleteMonths", PropertyValue = "0" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "SmarterLogsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterLogs" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "SmarterUrl", PropertyValue = "http://127.0.0.1:9999/services" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "StatisticsURL", PropertyValue = "http://127.0.0.1:9999/Login.aspx?txtSiteID=[site_id]&txtUser=[username]&txtPass=" +
                "[password]&shortcutLink=autologin" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "TimeZoneId", PropertyValue = "27" },
            new ServiceDefaultProperty() { ProviderId = 31, PropertyName = "Username", PropertyValue = "Admin" },
            new ServiceDefaultProperty() { ProviderId = 32, PropertyName = "KeepDeletedItemsDays", PropertyValue = "14" },
            new ServiceDefaultProperty() { ProviderId = 32, PropertyName = "KeepDeletedMailboxesDays", PropertyValue = "30" },
            new ServiceDefaultProperty() { ProviderId = 32, PropertyName = "MailboxDatabase", PropertyValue = "Hosted Exchange Database" },
            new ServiceDefaultProperty() { ProviderId = 32, PropertyName = "RootOU", PropertyValue = "SCP Hosting" },
            new ServiceDefaultProperty() { ProviderId = 32, PropertyName = "TempDomain", PropertyValue = "my-temp-domain.com" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "ExpireLimit", PropertyValue = "1209600" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "MinimumTTL", PropertyValue = "86400" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "NameServers", PropertyValue = "ns1.yourdomain.com;ns2.yourdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "PDNSDbName", PropertyValue = "pdnsdb" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "PDNSDbPort", PropertyValue = "3306" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "PDNSDbServer", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "PDNSDbUser", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "RefreshInterval", PropertyValue = "3600" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "ResponsiblePerson", PropertyValue = "hostmaster.[DOMAIN_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 56, PropertyName = "RetryDelay", PropertyValue = "600" },
            new ServiceDefaultProperty() { ProviderId = 60, PropertyName = "AdminPassword", PropertyValue = " " },
            new ServiceDefaultProperty() { ProviderId = 60, PropertyName = "AdminUsername", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 60, PropertyName = "DomainsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterMail" },
            new ServiceDefaultProperty() { ProviderId = 60, PropertyName = "ServerIPAddress", PropertyValue = "127.0.0.1;127.0.0.1" },
            new ServiceDefaultProperty() { ProviderId = 60, PropertyName = "ServiceUrl", PropertyValue = "http://localhost:9998/services/" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "LogDeleteDays", PropertyValue = "0" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "LogFormat", PropertyValue = "W3Cex" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "LogWildcard", PropertyValue = "*.log" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "Password", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "ServerID", PropertyValue = "1" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "SmarterLogDeleteMonths", PropertyValue = "0" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "SmarterLogsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterLogs" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "SmarterUrl", PropertyValue = "http://127.0.0.1:9999/services" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "StatisticsURL", PropertyValue = "http://127.0.0.1:9999/Login.aspx?txtSiteID=[site_id]&txtUser=[username]&txtPass=" +
                "[password]&shortcutLink=autologin" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "TimeZoneId", PropertyValue = "27" },
            new ServiceDefaultProperty() { ProviderId = 62, PropertyName = "Username", PropertyValue = "Admin" },
            new ServiceDefaultProperty() { ProviderId = 63, PropertyName = "AdminPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 63, PropertyName = "AdminUsername", PropertyValue = "Administrator" },
            new ServiceDefaultProperty() { ProviderId = 64, PropertyName = "AdminPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 64, PropertyName = "AdminUsername", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 64, PropertyName = "DomainsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterMail" },
            new ServiceDefaultProperty() { ProviderId = 64, PropertyName = "ServerIPAddress", PropertyValue = "127.0.0.1;127.0.0.1" },
            new ServiceDefaultProperty() { ProviderId = 64, PropertyName = "ServiceUrl", PropertyValue = "http://localhost:9998/services/" },
            new ServiceDefaultProperty() { ProviderId = 65, PropertyName = "AdminPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 65, PropertyName = "AdminUsername", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 65, PropertyName = "DomainsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterMail" },
            new ServiceDefaultProperty() { ProviderId = 65, PropertyName = "ServerIPAddress", PropertyValue = "127.0.0.1;127.0.0.1" },
            new ServiceDefaultProperty() { ProviderId = 65, PropertyName = "ServiceUrl", PropertyValue = "http://localhost:9998/services/" },
            new ServiceDefaultProperty() { ProviderId = 66, PropertyName = "AdminPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 66, PropertyName = "AdminUsername", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 66, PropertyName = "DomainsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterMail" },
            new ServiceDefaultProperty() { ProviderId = 66, PropertyName = "ServerIPAddress", PropertyValue = "127.0.0.1;127.0.0.1" },
            new ServiceDefaultProperty() { ProviderId = 66, PropertyName = "ServiceUrl", PropertyValue = "http://localhost:9998/services/" },
            new ServiceDefaultProperty() { ProviderId = 67, PropertyName = "AdminPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 67, PropertyName = "AdminUsername", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 67, PropertyName = "DomainsPath", PropertyValue = "%SYSTEMDRIVE%\\SmarterMail\\Domains" },
            new ServiceDefaultProperty() { ProviderId = 67, PropertyName = "ServerIPAddress", PropertyValue = "127.0.0.1;127.0.0.1" },
            new ServiceDefaultProperty() { ProviderId = 67, PropertyName = "ServiceUrl", PropertyValue = "http://localhost:9998" },
            new ServiceDefaultProperty() { ProviderId = 100, PropertyName = "UsersHome", PropertyValue = "%SYSTEMDRIVE%\\HostingSpaces" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "AspNet11Pool", PropertyValue = "ASP.NET 1.1" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "AspNet40Path", PropertyValue = "%WINDIR%\\Microsoft.NET\\Framework\\v4.0.30319\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "AspNet40x64Path", PropertyValue = "%WINDIR%\\Microsoft.NET\\Framework64\\v4.0.30319\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "AspNetBitnessMode", PropertyValue = "32" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "CFFlashRemotingDirectory", PropertyValue = "C:\\ColdFusion9\\untime\\lib\\wsconfig\\1" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "CFScriptsDirectory", PropertyValue = "C:\\Inetpub\\wwwroot\\CFIDE" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "ClassicAspNet20Pool", PropertyValue = "ASP.NET 2.0 (Classic)" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "ClassicAspNet40Pool", PropertyValue = "ASP.NET 4.0 (Classic)" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "ColdFusionPath", PropertyValue = "C:\\ColdFusion9\\untime\\lib\\wsconfig\\jrun_iis6.dll" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "GalleryXmlFeedUrl", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "IntegratedAspNet20Pool", PropertyValue = "ASP.NET 2.0 (Integrated)" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "IntegratedAspNet40Pool", PropertyValue = "ASP.NET 4.0 (Integrated)" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "PerlPath", PropertyValue = "%SYSTEMDRIVE%\\Perl\\bin\\PerlEx30.dll" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "Php4Path", PropertyValue = "%PROGRAMFILES(x86)%\\PHP\\php.exe" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "PhpMode", PropertyValue = "FastCGI" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "PhpPath", PropertyValue = "%PROGRAMFILES(x86)%\\PHP\\php-cgi.exe" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "ProtectedGroupsFile", PropertyValue = ".htgroup" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "ProtectedUsersFile", PropertyValue = ".htpasswd" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "SecureFoldersModuleAssembly", PropertyValue = "SolidCP.IIsModules.SecureFolders, SolidCP.IIsModules, Version=1.0.0.0, Culture=N" +
                "eutral, PublicKeyToken=37f9c58a0aa32ff0" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "WebGroupName", PropertyValue = "SCP_IUSRS" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "WmSvc.CredentialsMode", PropertyValue = "WINDOWS" },
            new ServiceDefaultProperty() { ProviderId = 101, PropertyName = "WmSvc.Port", PropertyValue = "8172" },
            new ServiceDefaultProperty() { ProviderId = 102, PropertyName = "FtpGroupName", PropertyValue = "SCPFtpUsers" },
            new ServiceDefaultProperty() { ProviderId = 102, PropertyName = "SiteId", PropertyValue = "Default FTP Site" },
            new ServiceDefaultProperty() { ProviderId = 104, PropertyName = "UsersHome", PropertyValue = "%SYSTEMDRIVE%\\HostingSpaces" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "AspNet11Pool", PropertyValue = "ASP.NET 1.1" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "AspNet40Path", PropertyValue = "%WINDIR%\\Microsoft.NET\\Framework\\v4.0.30319\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "AspNet40x64Path", PropertyValue = "%WINDIR%\\Microsoft.NET\\Framework64\\v4.0.30319\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "AspNetBitnessMode", PropertyValue = "32" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "CFFlashRemotingDirectory", PropertyValue = "C:\\ColdFusion9\\untime\\lib\\wsconfig\\1" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "CFScriptsDirectory", PropertyValue = "C:\\Inetpub\\wwwroot\\CFIDE" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "ClassicAspNet20Pool", PropertyValue = "ASP.NET 2.0 (Classic)" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "ClassicAspNet40Pool", PropertyValue = "ASP.NET 4.0 (Classic)" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "ColdFusionPath", PropertyValue = "C:\\ColdFusion9\\untime\\lib\\wsconfig\\jrun_iis6.dll" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "GalleryXmlFeedUrl", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "IntegratedAspNet20Pool", PropertyValue = "ASP.NET 2.0 (Integrated)" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "IntegratedAspNet40Pool", PropertyValue = "ASP.NET 4.0 (Integrated)" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "PerlPath", PropertyValue = "%SYSTEMDRIVE%\\Perl\\bin\\PerlEx30.dll" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "Php4Path", PropertyValue = "%PROGRAMFILES(x86)%\\PHP\\php.exe" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "PhpMode", PropertyValue = "FastCGI" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "PhpPath", PropertyValue = "%PROGRAMFILES(x86)%\\PHP\\php-cgi.exe" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "ProtectedGroupsFile", PropertyValue = ".htgroup" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "ProtectedUsersFile", PropertyValue = ".htpasswd" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "SecureFoldersModuleAssembly", PropertyValue = "SolidCP.IIsModules.SecureFolders, SolidCP.IIsModules, Version=1.0.0.0, Culture=N" +
                "eutral, PublicKeyToken=37f9c58a0aa32ff0" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "sslusesni", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "WebGroupName", PropertyValue = "SCP_IUSRS" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "WmSvc.CredentialsMode", PropertyValue = "WINDOWS" },
            new ServiceDefaultProperty() { ProviderId = 105, PropertyName = "WmSvc.Port", PropertyValue = "8172" },
            new ServiceDefaultProperty() { ProviderId = 106, PropertyName = "FtpGroupName", PropertyValue = "SCPFtpUsers" },
            new ServiceDefaultProperty() { ProviderId = 106, PropertyName = "SiteId", PropertyValue = "Default FTP Site" },
            new ServiceDefaultProperty() { ProviderId = 106, PropertyName = "sslusesni", PropertyValue = "False" },
            new ServiceDefaultProperty() { ProviderId = 111, PropertyName = "UsersHome", PropertyValue = "%SYSTEMDRIVE%\\HostingSpaces" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "AspNet11Pool", PropertyValue = "ASP.NET 1.1" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "AspNet40Path", PropertyValue = "%WINDIR%\\Microsoft.NET\\Framework\\v4.0.30319\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "AspNet40x64Path", PropertyValue = "%WINDIR%\\Microsoft.NET\\Framework64\\v4.0.30319\\aspnet_isapi.dll" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "AspNetBitnessMode", PropertyValue = "32" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "CFFlashRemotingDirectory", PropertyValue = "C:\\ColdFusion9\\untime\\lib\\wsconfig\\1" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "CFScriptsDirectory", PropertyValue = "C:\\Inetpub\\wwwroot\\CFIDE" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "ClassicAspNet20Pool", PropertyValue = "ASP.NET 2.0 (Classic)" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "ClassicAspNet40Pool", PropertyValue = "ASP.NET 4.0 (Classic)" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "ColdFusionPath", PropertyValue = "C:\\ColdFusion9\\untime\\lib\\wsconfig\\jrun_iis6.dll" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "GalleryXmlFeedUrl", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "IntegratedAspNet20Pool", PropertyValue = "ASP.NET 2.0 (Integrated)" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "IntegratedAspNet40Pool", PropertyValue = "ASP.NET 4.0 (Integrated)" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "PerlPath", PropertyValue = "%SYSTEMDRIVE%\\Perl\\bin\\PerlEx30.dll" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "Php4Path", PropertyValue = "%PROGRAMFILES(x86)%\\PHP\\php.exe" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "PhpMode", PropertyValue = "FastCGI" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "PhpPath", PropertyValue = "%PROGRAMFILES(x86)%\\PHP\\php-cgi.exe" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "ProtectedGroupsFile", PropertyValue = ".htgroup" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "ProtectedUsersFile", PropertyValue = ".htpasswd" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "SecureFoldersModuleAssembly", PropertyValue = "SolidCP.IIsModules.SecureFolders, SolidCP.IIsModules, Version=1.0.0.0, Culture=N" +
                "eutral, PublicKeyToken=37f9c58a0aa32ff0" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "sslusesni", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "WebGroupName", PropertyValue = "SCP_IUSRS" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "WmSvc.CredentialsMode", PropertyValue = "WINDOWS" },
            new ServiceDefaultProperty() { ProviderId = 112, PropertyName = "WmSvc.Port", PropertyValue = "8172" },
            new ServiceDefaultProperty() { ProviderId = 113, PropertyName = "FtpGroupName", PropertyValue = "SCPFtpUsers" },
            new ServiceDefaultProperty() { ProviderId = 113, PropertyName = "SiteId", PropertyValue = "Default FTP Site" },
            new ServiceDefaultProperty() { ProviderId = 113, PropertyName = "sslusesni", PropertyValue = "False" },
            new ServiceDefaultProperty() { ProviderId = 200, PropertyName = "RootWebApplicationIpAddress", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 204, PropertyName = "UserName", PropertyValue = "admin" },
            new ServiceDefaultProperty() { ProviderId = 204, PropertyName = "UtilityPath", PropertyValue = "C:\\Program Files\\Research In Motion\\BlackBerry Enterprise Server Resource Kit\\Bl" +
                "ackBerry Enterprise Server User Administration Tool" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "CpuLimit", PropertyValue = "100" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "CpuReserve", PropertyValue = "0" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "CpuWeight", PropertyValue = "100" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "DvdLibraryPath", PropertyValue = "C:\\Hyper-V\\Library" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "ExportedVpsPath", PropertyValue = "C:\\Hyper-V\\Exported" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "HostnamePattern", PropertyValue = "vps[user_id].hosterdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "OsTemplatesPath", PropertyValue = "C:\\Hyper-V\\Templates" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "PrivateNetworkFormat", PropertyValue = "192.168.0.1/16" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "RootFolder", PropertyValue = "C:\\Hyper-V\\VirtualMachines\\[VPS_HOSTNAME]" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "StartAction", PropertyValue = "start" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "StartupDelay", PropertyValue = "0" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "StopAction", PropertyValue = "shutDown" },
            new ServiceDefaultProperty() { ProviderId = 300, PropertyName = "VirtualDiskType", PropertyValue = "dynamic" },
            new ServiceDefaultProperty() { ProviderId = 301, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 301, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MySQL\\MySQL Server 5.5" },
            new ServiceDefaultProperty() { ProviderId = 301, PropertyName = "InternalAddress", PropertyValue = "localhost,3306" },
            new ServiceDefaultProperty() { ProviderId = 301, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 301, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 304, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 304, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MySQL\\MySQL Server 8.0" },
            new ServiceDefaultProperty() { ProviderId = 304, PropertyName = "InternalAddress", PropertyValue = "localhost,3306" },
            new ServiceDefaultProperty() { ProviderId = 304, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 304, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 304, PropertyName = "sslmode", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 305, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 305, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MySQL\\MySQL Server 8.0" },
            new ServiceDefaultProperty() { ProviderId = 305, PropertyName = "InternalAddress", PropertyValue = "localhost,3306" },
            new ServiceDefaultProperty() { ProviderId = 305, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 305, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 305, PropertyName = "sslmode", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 306, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 306, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MySQL\\MySQL Server 8.0" },
            new ServiceDefaultProperty() { ProviderId = 306, PropertyName = "InternalAddress", PropertyValue = "localhost,3306" },
            new ServiceDefaultProperty() { ProviderId = 306, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 306, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 306, PropertyName = "sslmode", PropertyValue = "True" },
            new ServiceDefaultProperty() { ProviderId = 410, PropertyName = "admode", PropertyValue = "False" },
            new ServiceDefaultProperty() { ProviderId = 410, PropertyName = "expirelimit", PropertyValue = "1209600" },
            new ServiceDefaultProperty() { ProviderId = 410, PropertyName = "minimumttl", PropertyValue = "86400" },
            new ServiceDefaultProperty() { ProviderId = 410, PropertyName = "nameservers", PropertyValue = "ns1.yourdomain.com;ns2.yourdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 410, PropertyName = "refreshinterval", PropertyValue = "3600" },
            new ServiceDefaultProperty() { ProviderId = 410, PropertyName = "responsibleperson", PropertyValue = "hostmaster.[DOMAIN_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 410, PropertyName = "retrydelay", PropertyValue = "600" },
            new ServiceDefaultProperty() { ProviderId = 500, PropertyName = "LogDir", PropertyValue = "/var/log" },
            new ServiceDefaultProperty() { ProviderId = 500, PropertyName = "UsersHome", PropertyValue = "%HOME%" },
            new ServiceDefaultProperty() { ProviderId = 1550, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1550, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MariaDB 10.1" },
            new ServiceDefaultProperty() { ProviderId = 1550, PropertyName = "InternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1550, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 1550, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 1570, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1570, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MariaDB 10.3" },
            new ServiceDefaultProperty() { ProviderId = 1570, PropertyName = "InternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1570, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 1570, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 1571, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1571, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MariaDB 10.4" },
            new ServiceDefaultProperty() { ProviderId = 1571, PropertyName = "InternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1571, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 1571, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 1572, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1572, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MariaDB 10.5" },
            new ServiceDefaultProperty() { ProviderId = 1572, PropertyName = "InternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1572, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 1572, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 1573, PropertyName = "ExternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1573, PropertyName = "InstallFolder", PropertyValue = "%PROGRAMFILES%\\MariaDB 10.5" },
            new ServiceDefaultProperty() { ProviderId = 1573, PropertyName = "InternalAddress", PropertyValue = "localhost" },
            new ServiceDefaultProperty() { ProviderId = 1573, PropertyName = "RootLogin", PropertyValue = "root" },
            new ServiceDefaultProperty() { ProviderId = 1573, PropertyName = "RootPassword", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 1800, PropertyName = "UsersHome", PropertyValue = "%SYSTEMDRIVE%\\HostingSpaces" },
            new ServiceDefaultProperty() { ProviderId = 1802, PropertyName = "UsersHome", PropertyValue = "%SYSTEMDRIVE%\\HostingSpaces" },
            new ServiceDefaultProperty() { ProviderId = 1901, PropertyName = "AdminLogin", PropertyValue = "Admin" },
            new ServiceDefaultProperty() { ProviderId = 1901, PropertyName = "ExpireLimit", PropertyValue = "1209600" },
            new ServiceDefaultProperty() { ProviderId = 1901, PropertyName = "MinimumTTL", PropertyValue = "86400" },
            new ServiceDefaultProperty() { ProviderId = 1901, PropertyName = "NameServers", PropertyValue = "ns1.yourdomain.com;ns2.yourdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 1901, PropertyName = "RefreshInterval", PropertyValue = "3600" },
            new ServiceDefaultProperty() { ProviderId = 1901, PropertyName = "ResponsiblePerson", PropertyValue = "hostmaster.[DOMAIN_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 1901, PropertyName = "RetryDelay", PropertyValue = "600" },
            new ServiceDefaultProperty() { ProviderId = 1901, PropertyName = "SimpleDnsUrl", PropertyValue = "http://127.0.0.1:8053" },
            new ServiceDefaultProperty() { ProviderId = 1902, PropertyName = "admode", PropertyValue = "False" },
            new ServiceDefaultProperty() { ProviderId = 1902, PropertyName = "expirelimit", PropertyValue = "1209600" },
            new ServiceDefaultProperty() { ProviderId = 1902, PropertyName = "minimumttl", PropertyValue = "86400" },
            new ServiceDefaultProperty() { ProviderId = 1902, PropertyName = "nameservers", PropertyValue = "ns1.yourdomain.com;ns2.yourdomain.com" },
            new ServiceDefaultProperty() { ProviderId = 1902, PropertyName = "refreshinterval", PropertyValue = "3600" },
            new ServiceDefaultProperty() { ProviderId = 1902, PropertyName = "responsibleperson", PropertyValue = "hostmaster.[DOMAIN_NAME]" },
            new ServiceDefaultProperty() { ProviderId = 1902, PropertyName = "retrydelay", PropertyValue = "600" },
            new ServiceDefaultProperty() { ProviderId = 1910, PropertyName = "ConfigFile", PropertyValue = "/etc/vsftpd.conf" },
            new ServiceDefaultProperty() { ProviderId = 1911, PropertyName = "BinPath", PropertyValue = "" },
            new ServiceDefaultProperty() { ProviderId = 1911, PropertyName = "ConfigFile", PropertyValue = "/etc/apache2/apache2.conf" },
            new ServiceDefaultProperty() { ProviderId = 1911, PropertyName = "ConfigPath", PropertyValue = "/etc/apache2" }
        });
        #endregion

    }
}
