//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidCP.WebDavPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidCP.WebDavPortal.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was not found.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in use.
        /// </summary>
        public static string AlreadyInUse {
            get {
                return ResourceManager.GetString("AlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password could not be reset. The url you followed is either incorrect, has been used or has expired..
        /// </summary>
        public static string IncorrectPasswordResetUrl {
            get {
                return ResourceManager.GetString("IncorrectPasswordResetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect text message (SMS) response..
        /// </summary>
        public static string IncorrectSmsResponse {
            get {
                return ResourceManager.GetString("IncorrectSmsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is not correct.
        /// </summary>
        public static string OldPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("OldPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordDoesntMatch {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be maximum {0} characters.
        /// </summary>
        public static string PasswordMaxLengthFormat {
            get {
                return ResourceManager.GetString("PasswordMaxLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be at least {0} characters.
        /// </summary>
        public static string PasswordMinLengthFormat {
            get {
                return ResourceManager.GetString("PasswordMinLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain at least {0} numbers.
        /// </summary>
        public static string PasswordNumbersCountFormat {
            get {
                return ResourceManager.GetString("PasswordNumbersCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message was sent to your email address. Please check your email for further instructions..
        /// </summary>
        public static string PasswordResetEmailSent {
            get {
                return ResourceManager.GetString("PasswordResetEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the verification code we sent to you. If you didn&apos;t receive a code, you can {0}..
        /// </summary>
        public static string PasswordResetSmsHintFormat {
            get {
                return ResourceManager.GetString("PasswordResetSmsHintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webdav portal user request..
        /// </summary>
        public static string PasswordResetUserReason {
            get {
                return ResourceManager.GetString("PasswordResetUserReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password have been successfully changed.
        /// </summary>
        public static string PasswordSuccessfullyChanged {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain at least {0} non-alphanumeric symbols.
        /// </summary>
        public static string PasswordSymbolsCountFormat {
            get {
                return ResourceManager.GetString("PasswordSymbolsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain at least {0} UPPERCASE characters.
        /// </summary>
        public static string PasswordUppercaseCountFormat {
            get {
                return ResourceManager.GetString("PasswordUppercaseCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincode was not sent to your email address..
        /// </summary>
        public static string PincodeEmailWasNotSent {
            get {
                return ResourceManager.GetString("PincodeEmailWasNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincode was sent to your email address..
        /// </summary>
        public static string PincodeEmailWasSent {
            get {
                return ResourceManager.GetString("PincodeEmailWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text message (SMS) was not sent to your mobile phone. Invalid phone number..
        /// </summary>
        public static string SmsWasNotSent {
            get {
                return ResourceManager.GetString("SmsWasNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text message (SMS) was sent to your mobile phone..
        /// </summary>
        public static string SmsWasSent {
            get {
                return ResourceManager.GetString("SmsWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is invalid.
        /// </summary>
        public static string UrlInvalid {
            get {
                return ResourceManager.GetString("UrlInvalid", resourceCulture);
            }
        }
    }
}
